/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables


import co.spoonradio.sims.repository.billing.DefaultSchema
import co.spoonradio.sims.repository.billing.keys.PK_EXCHANGEAMOUNT_ID
import co.spoonradio.sims.repository.billing.tables.records.TbexchangeamountRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tbexchangeamount(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TbexchangeamountRecord>?,
    aliased: Table<TbexchangeamountRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TbexchangeamountRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tbExchangeAmount</code>
         */
        val TBEXCHANGEAMOUNT = Tbexchangeamount()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TbexchangeamountRecord> = TbexchangeamountRecord::class.java

    /**
     * The column <code>tbExchangeAmount.id</code>.
     */
    val ID: TableField<TbexchangeamountRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>tbExchangeAmount.exchangeId</code>.
     */
    val EXCHANGEID: TableField<TbexchangeamountRecord, Long?> = createField(DSL.name("exchangeId"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>tbExchangeAmount.balanceLockId</code>.
     */
    val BALANCELOCKID: TableField<TbexchangeamountRecord, String?> = createField(DSL.name("balanceLockId"), SQLDataType.CHAR(32).nullable(false), this, "")

    /**
     * The column <code>tbExchangeAmount.currency</code>.
     */
    val CURRENCY: TableField<TbexchangeamountRecord, String?> = createField(DSL.name("currency"), SQLDataType.CHAR(3), this, "")

    /**
     * The column <code>tbExchangeAmount.exchangeSpoon</code>.
     */
    val EXCHANGESPOON: TableField<TbexchangeamountRecord, Long?> = createField(DSL.name("exchangeSpoon"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>tbExchangeAmount.amount</code>.
     */
    val AMOUNT: TableField<TbexchangeamountRecord, Long?> = createField(DSL.name("amount"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>tbExchangeAmount.status</code>.
     */
    val STATUS: TableField<TbexchangeamountRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(15).nullable(false), this, "")

    /**
     * The column <code>tbExchangeAmount.created</code>.
     */
    val CREATED: TableField<TbexchangeamountRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>tbExchangeAmount.updated</code>.
     */
    val UPDATED: TableField<TbexchangeamountRecord, LocalDateTime?> = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<TbexchangeamountRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TbexchangeamountRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tbExchangeAmount</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tbExchangeAmount</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tbExchangeAmount</code> table reference
     */
    constructor(): this(DSL.name("tbExchangeAmount"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TbexchangeamountRecord>): this(Internal.createPathAlias(child, key), child, key, TBEXCHANGEAMOUNT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TbexchangeamountRecord, Long?> = super.getIdentity() as Identity<TbexchangeamountRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TbexchangeamountRecord> = PK_EXCHANGEAMOUNT_ID
    override fun getKeys(): List<UniqueKey<TbexchangeamountRecord>> = listOf(PK_EXCHANGEAMOUNT_ID)
    override fun `as`(alias: String): Tbexchangeamount = Tbexchangeamount(DSL.name(alias), this)
    override fun `as`(alias: Name): Tbexchangeamount = Tbexchangeamount(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tbexchangeamount = Tbexchangeamount(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tbexchangeamount = Tbexchangeamount(name, null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<Long?, Long?, String?, String?, Long?, Long?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row9<Long?, Long?, String?, String?, Long?, Long?, String?, LocalDateTime?, LocalDateTime?>
}
