/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables


import co.spoonradio.sims.repository.billing.DefaultSchema
import co.spoonradio.sims.repository.billing.keys.CONSTRAINT_F
import co.spoonradio.sims.repository.billing.tables.records.TbexchangehistoryRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tbexchangehistory(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TbexchangehistoryRecord>?,
    aliased: Table<TbexchangehistoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TbexchangehistoryRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tbExchangeHistory</code>
         */
        val TBEXCHANGEHISTORY = Tbexchangehistory()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TbexchangehistoryRecord> = TbexchangehistoryRecord::class.java

    /**
     * The column <code>tbExchangeHistory.id</code>.
     */
    val ID: TableField<TbexchangehistoryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>tbExchangeHistory.exchangeId</code>.
     */
    val EXCHANGEID: TableField<TbexchangehistoryRecord, Long?> = createField(DSL.name("exchangeId"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>tbExchangeHistory.status</code>.
     */
    val STATUS: TableField<TbexchangehistoryRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(15).nullable(false), this, "")

    /**
     * The column <code>tbExchangeHistory.created</code>.
     */
    val CREATED: TableField<TbexchangehistoryRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<TbexchangehistoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TbexchangehistoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tbExchangeHistory</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tbExchangeHistory</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tbExchangeHistory</code> table reference
     */
    constructor(): this(DSL.name("tbExchangeHistory"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TbexchangehistoryRecord>): this(Internal.createPathAlias(child, key), child, key, TBEXCHANGEHISTORY, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TbexchangehistoryRecord, Long?> = super.getIdentity() as Identity<TbexchangehistoryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TbexchangehistoryRecord> = CONSTRAINT_F
    override fun getKeys(): List<UniqueKey<TbexchangehistoryRecord>> = listOf(CONSTRAINT_F)
    override fun `as`(alias: String): Tbexchangehistory = Tbexchangehistory(DSL.name(alias), this)
    override fun `as`(alias: Name): Tbexchangehistory = Tbexchangehistory(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tbexchangehistory = Tbexchangehistory(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tbexchangehistory = Tbexchangehistory(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, String?, LocalDateTime?> = super.fieldsRow() as Row4<Long?, Long?, String?, LocalDateTime?>
}
