/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables


import co.spoonradio.sims.repository.billing.DefaultSchema
import co.spoonradio.sims.repository.billing.keys.PK_EXCHANGESUBMITDOCUMENT_ID
import co.spoonradio.sims.repository.billing.tables.records.TbexchangesubmitdocumentRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tbexchangesubmitdocument(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TbexchangesubmitdocumentRecord>?,
    aliased: Table<TbexchangesubmitdocumentRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TbexchangesubmitdocumentRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tbExchangeSubmitDocument</code>
         */
        val TBEXCHANGESUBMITDOCUMENT = Tbexchangesubmitdocument()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TbexchangesubmitdocumentRecord> = TbexchangesubmitdocumentRecord::class.java

    /**
     * The column <code>tbExchangeSubmitDocument.id</code>.
     */
    val ID: TableField<TbexchangesubmitdocumentRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>tbExchangeSubmitDocument.exchangeId</code>.
     */
    val EXCHANGEID: TableField<TbexchangesubmitdocumentRecord, Long?> = createField(DSL.name("exchangeId"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>tbExchangeSubmitDocument.type</code>.
     */
    val TYPE: TableField<TbexchangesubmitdocumentRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>tbExchangeSubmitDocument.url</code>.
     */
    val URL: TableField<TbexchangesubmitdocumentRecord, String?> = createField(DSL.name("url"), SQLDataType.VARCHAR(256).nullable(false), this, "")

    /**
     * The column <code>tbExchangeSubmitDocument.created</code>.
     */
    val CREATED: TableField<TbexchangesubmitdocumentRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<TbexchangesubmitdocumentRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TbexchangesubmitdocumentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tbExchangeSubmitDocument</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tbExchangeSubmitDocument</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tbExchangeSubmitDocument</code> table reference
     */
    constructor(): this(DSL.name("tbExchangeSubmitDocument"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TbexchangesubmitdocumentRecord>): this(Internal.createPathAlias(child, key), child, key, TBEXCHANGESUBMITDOCUMENT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TbexchangesubmitdocumentRecord, Long?> = super.getIdentity() as Identity<TbexchangesubmitdocumentRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TbexchangesubmitdocumentRecord> = PK_EXCHANGESUBMITDOCUMENT_ID
    override fun getKeys(): List<UniqueKey<TbexchangesubmitdocumentRecord>> = listOf(PK_EXCHANGESUBMITDOCUMENT_ID)
    override fun `as`(alias: String): Tbexchangesubmitdocument = Tbexchangesubmitdocument(DSL.name(alias), this)
    override fun `as`(alias: Name): Tbexchangesubmitdocument = Tbexchangesubmitdocument(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tbexchangesubmitdocument = Tbexchangesubmitdocument(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tbexchangesubmitdocument = Tbexchangesubmitdocument(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Long?, Long?, String?, String?, LocalDateTime?> = super.fieldsRow() as Row5<Long?, Long?, String?, String?, LocalDateTime?>
}
