/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables


import co.spoonradio.sims.repository.billing.DefaultSchema
import co.spoonradio.sims.repository.billing.keys.PK_ITEMSTORE_ID
import co.spoonradio.sims.repository.billing.tables.records.TbitemstoreRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tbitemstore(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TbitemstoreRecord>?,
    aliased: Table<TbitemstoreRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TbitemstoreRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tbItemStore</code>
         */
        val TBITEMSTORE = Tbitemstore()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TbitemstoreRecord> = TbitemstoreRecord::class.java

    /**
     * The column <code>tbItemStore.id</code>.
     */
    val ID: TableField<TbitemstoreRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>tbItemStore.rewardId</code>.
     */
    val REWARDID: TableField<TbitemstoreRecord, Int?> = createField(DSL.name("rewardId"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbItemStore.productId</code>.
     */
    val PRODUCTID: TableField<TbitemstoreRecord, Int?> = createField(DSL.name("productId"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbItemStore.creator</code>.
     */
    val CREATOR: TableField<TbitemstoreRecord, Int?> = createField(DSL.name("creator"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbItemStore.updater</code>.
     */
    val UPDATER: TableField<TbitemstoreRecord, Int?> = createField(DSL.name("updater"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>tbItemStore.createdDate</code>.
     */
    val CREATEDDATE: TableField<TbitemstoreRecord, LocalDateTime?> = createField(DSL.name("createdDate"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>tbItemStore.updatedDate</code>.
     */
    val UPDATEDDATE: TableField<TbitemstoreRecord, LocalDateTime?> = createField(DSL.name("updatedDate"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>tbItemStore.isUse</code>.
     */
    val ISUSE: TableField<TbitemstoreRecord, Boolean?> = createField(DSL.name("isUse"), SQLDataType.BOOLEAN.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TbitemstoreRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TbitemstoreRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tbItemStore</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tbItemStore</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tbItemStore</code> table reference
     */
    constructor(): this(DSL.name("tbItemStore"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TbitemstoreRecord>): this(Internal.createPathAlias(child, key), child, key, TBITEMSTORE, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TbitemstoreRecord, Long?> = super.getIdentity() as Identity<TbitemstoreRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TbitemstoreRecord> = PK_ITEMSTORE_ID
    override fun getKeys(): List<UniqueKey<TbitemstoreRecord>> = listOf(PK_ITEMSTORE_ID)
    override fun `as`(alias: String): Tbitemstore = Tbitemstore(DSL.name(alias), this)
    override fun `as`(alias: Name): Tbitemstore = Tbitemstore(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tbitemstore = Tbitemstore(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tbitemstore = Tbitemstore(name, null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Long?, Int?, Int?, Int?, Int?, LocalDateTime?, LocalDateTime?, Boolean?> = super.fieldsRow() as Row8<Long?, Int?, Int?, Int?, Int?, LocalDateTime?, LocalDateTime?, Boolean?>
}
