/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables


import co.spoonradio.sims.repository.billing.DefaultSchema
import co.spoonradio.sims.repository.billing.keys.PK_SOFTBANK_HISTORY_ID
import co.spoonradio.sims.repository.billing.keys.UIDX_SOFTBANK_HISTORY_ORDER_ID
import co.spoonradio.sims.repository.billing.tables.records.TbsoftbankhistoryRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row21
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tbsoftbankhistory(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TbsoftbankhistoryRecord>?,
    aliased: Table<TbsoftbankhistoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TbsoftbankhistoryRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tbSoftBankHistory</code>
         */
        val TBSOFTBANKHISTORY = Tbsoftbankhistory()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TbsoftbankhistoryRecord> = TbsoftbankhistoryRecord::class.java

    /**
     * The column <code>tbSoftBankHistory.id</code>.
     */
    val ID: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>tbSoftBankHistory.status</code>.
     */
    val STATUS: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.txId</code>.
     */
    val TXID: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("txId"), SQLDataType.VARCHAR(64).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>tbSoftBankHistory.payMethod</code>.
     */
    val PAYMETHOD: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("payMethod"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.orderId</code>.
     */
    val ORDERID: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("orderId"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.tax</code>.
     */
    val TAX: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("tax"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.payType</code>.
     */
    val PAYTYPE: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("payType"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.limitSecond</code>.
     */
    val LIMITSECOND: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("limitSecond"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.spsHashcode</code>.
     */
    val SPSHASHCODE: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("spsHashcode"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.userAgent</code>.
     */
    val USERAGENT: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("userAgent"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.errorCode</code>.
     */
    val ERRORCODE: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("errorCode"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.resResult</code>.
     */
    val RESRESULT: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("resResult"), SQLDataType.VARCHAR(2).nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.requestDate</code>.
     */
    val REQUESTDATE: TableField<TbsoftbankhistoryRecord, String?> = createField(DSL.name("requestDate"), SQLDataType.VARCHAR(20).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>tbSoftBankHistory.completed</code>.
     */
    val COMPLETED: TableField<TbsoftbankhistoryRecord, LocalDateTime?> = createField(DSL.name("completed"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("NULL", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>tbSoftBankHistory.created</code>.
     */
    val CREATED: TableField<TbsoftbankhistoryRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("NULL", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>tbSoftBankHistory.productId</code>.
     */
    val PRODUCTID: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("productId"), SQLDataType.INTEGER.defaultValue(DSL.field("NULL", SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>tbSoftBankHistory.promotionId</code>.
     */
    val PROMOTIONID: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("promotionId"), SQLDataType.INTEGER.defaultValue(DSL.field("NULL", SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>tbSoftBankHistory.userId</code>.
     */
    val USERID: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("userId"), SQLDataType.INTEGER.defaultValue(DSL.field("NULL", SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>tbSoftBankHistory.amount</code>.
     */
    val AMOUNT: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("amount"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>tbSoftBankHistory.quantity</code>.
     */
    val QUANTITY: TableField<TbsoftbankhistoryRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.defaultValue(DSL.field("NULL", SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>tbSoftBankHistory.updated</code>.
     */
    val UPDATED: TableField<TbsoftbankhistoryRecord, LocalDateTime?> = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("NULL", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<TbsoftbankhistoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TbsoftbankhistoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tbSoftBankHistory</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tbSoftBankHistory</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tbSoftBankHistory</code> table reference
     */
    constructor(): this(DSL.name("tbSoftBankHistory"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TbsoftbankhistoryRecord>): this(Internal.createPathAlias(child, key), child, key, TBSOFTBANKHISTORY, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TbsoftbankhistoryRecord, Int?> = super.getIdentity() as Identity<TbsoftbankhistoryRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TbsoftbankhistoryRecord> = PK_SOFTBANK_HISTORY_ID
    override fun getKeys(): List<UniqueKey<TbsoftbankhistoryRecord>> = listOf(PK_SOFTBANK_HISTORY_ID, UIDX_SOFTBANK_HISTORY_ORDER_ID)
    override fun `as`(alias: String): Tbsoftbankhistory = Tbsoftbankhistory(DSL.name(alias), this)
    override fun `as`(alias: Name): Tbsoftbankhistory = Tbsoftbankhistory(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tbsoftbankhistory = Tbsoftbankhistory(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tbsoftbankhistory = Tbsoftbankhistory(name, null)

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?> = super.fieldsRow() as Row21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?>
}
