/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tbexchangeamount(
    val id: Long? = null, 
    val exchangeid: Long? = null, 
    val balancelockid: String? = null, 
    val currency: String? = null, 
    val exchangespoon: Long? = null, 
    val amount: Long? = null, 
    val status: String? = null, 
    val created: LocalDateTime? = null, 
    val updated: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Tbexchangeamount (")

        sb.append(id)
        sb.append(", ").append(exchangeid)
        sb.append(", ").append(balancelockid)
        sb.append(", ").append(currency)
        sb.append(", ").append(exchangespoon)
        sb.append(", ").append(amount)
        sb.append(", ").append(status)
        sb.append(", ").append(created)
        sb.append(", ").append(updated)

        sb.append(")")
        return sb.toString()
    }
}
