/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tbexchangehistory(
    val id: Long? = null, 
    val exchangeid: Long? = null, 
    val status: String? = null, 
    val created: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Tbexchangehistory (")

        sb.append(id)
        sb.append(", ").append(exchangeid)
        sb.append(", ").append(status)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
