/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tbexchangedotmoneysignaturedata(
    val userid: Long? = null, 
    val signature: String? = null, 
    val exchangeddotmoneypoint: Long? = null, 
    val exchangedspoon: Long? = null, 
    val username: String? = null, 
    val expireat: LocalDateTime? = null, 
    val created: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Tbexchangedotmoneysignaturedata (")

        sb.append(userid)
        sb.append(", ").append(signature)
        sb.append(", ").append(exchangeddotmoneypoint)
        sb.append(", ").append(exchangedspoon)
        sb.append(", ").append(username)
        sb.append(", ").append(expireat)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
