/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.pojos


import java.io.Serializable
import java.time.LocalDate
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tbexchange(
    val id: Long? = null, 
    val applicantid: Long? = null, 
    val methodtype: String? = null, 
    val totalexchangespoon: Long? = null, 
    val currency: String? = null, 
    val totalexchangeamount: Long? = null, 
    val estimatedexchangeamount: Long? = null, 
    val expectedexchangeddate: LocalDate? = null, 
    val status: String? = null, 
    val created: LocalDateTime? = null, 
    val updated: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Tbexchange (")

        sb.append(id)
        sb.append(", ").append(applicantid)
        sb.append(", ").append(methodtype)
        sb.append(", ").append(totalexchangespoon)
        sb.append(", ").append(currency)
        sb.append(", ").append(totalexchangeamount)
        sb.append(", ").append(estimatedexchangeamount)
        sb.append(", ").append(expectedexchangeddate)
        sb.append(", ").append(status)
        sb.append(", ").append(created)
        sb.append(", ").append(updated)

        sb.append(")")
        return sb.toString()
    }
}
