/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tbgiftcardhistory(
    val id: Int? = null, 
    val paymethod: String? = null, 
    val txid: String? = null, 
    val status: String? = null, 
    val giftcardnumber: String? = null, 
    val amount: Int? = null, 
    val userid: Int? = null, 
    val createddate: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Tbgiftcardhistory (")

        sb.append(id)
        sb.append(", ").append(paymethod)
        sb.append(", ").append(txid)
        sb.append(", ").append(status)
        sb.append(", ").append(giftcardnumber)
        sb.append(", ").append(amount)
        sb.append(", ").append(userid)
        sb.append(", ").append(createddate)

        sb.append(")")
        return sb.toString()
    }
}
