/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tbitempromotion(
    val id: Int? = null, 
    val name: String? = null, 
    val code: String? = null, 
    val value: Int? = null, 
    val isuse: Boolean? = null, 
    val startdate: LocalDateTime? = null, 
    val enddate: LocalDateTime? = null, 
    val createddate: LocalDateTime? = null, 
    val updateddate: LocalDateTime? = null, 
    val creator: Int? = null, 
    val updater: Int? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Tbitempromotion (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(code)
        sb.append(", ").append(value)
        sb.append(", ").append(isuse)
        sb.append(", ").append(startdate)
        sb.append(", ").append(enddate)
        sb.append(", ").append(createddate)
        sb.append(", ").append(updateddate)
        sb.append(", ").append(creator)
        sb.append(", ").append(updater)

        sb.append(")")
        return sb.toString()
    }
}
