/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables


import co.spoonradio.sims.repository.postgresql.DefaultSchema
import co.spoonradio.sims.repository.postgresql.keys.CASTS_TEXTCOMMENT_PKEY
import co.spoonradio.sims.repository.postgresql.tables.records.CastsTextcommentRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CastsTextcomment(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CastsTextcommentRecord>?,
    aliased: Table<CastsTextcommentRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CastsTextcommentRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>casts_textcomment</code>
         */
        val CASTS_TEXTCOMMENT = CastsTextcomment()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CastsTextcommentRecord> = CastsTextcommentRecord::class.java

    /**
     * The column <code>casts_textcomment.id</code>.
     */
    val ID: TableField<CastsTextcommentRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>casts_textcomment.contents</code>.
     */
    val CONTENTS: TableField<CastsTextcommentRecord, String?> = createField(DSL.name("contents"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>casts_textcomment.reporters</code>.
     */
    val REPORTERS: TableField<CastsTextcommentRecord, Array<Any?>?> = createField(DSL.name("reporters"), SQLDataType.OTHER.getArrayDataType(), this, "")

    /**
     * The column <code>casts_textcomment.created</code>.
     */
    val CREATED: TableField<CastsTextcommentRecord, OffsetDateTime?> = createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>casts_textcomment.author_id</code>.
     */
    val AUTHOR_ID: TableField<CastsTextcommentRecord, Int?> = createField(DSL.name("author_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>casts_textcomment.cast_id</code>.
     */
    val CAST_ID: TableField<CastsTextcommentRecord, Int?> = createField(DSL.name("cast_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>casts_textcomment.to_user_id</code>.
     */
    val TO_USER_ID: TableField<CastsTextcommentRecord, Int?> = createField(DSL.name("to_user_id"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<CastsTextcommentRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CastsTextcommentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>casts_textcomment</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>casts_textcomment</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>casts_textcomment</code> table reference
     */
    constructor(): this(DSL.name("casts_textcomment"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CastsTextcommentRecord>): this(Internal.createPathAlias(child, key), child, key, CASTS_TEXTCOMMENT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<CastsTextcommentRecord, Int?> = super.getIdentity() as Identity<CastsTextcommentRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<CastsTextcommentRecord> = CASTS_TEXTCOMMENT_PKEY
    override fun getKeys(): List<UniqueKey<CastsTextcommentRecord>> = listOf(CASTS_TEXTCOMMENT_PKEY)
    override fun `as`(alias: String): CastsTextcomment = CastsTextcomment(DSL.name(alias), this)
    override fun `as`(alias: Name): CastsTextcomment = CastsTextcomment(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CastsTextcomment = CastsTextcomment(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CastsTextcomment = CastsTextcomment(name, null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Int?, String?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?> = super.fieldsRow() as Row7<Int?, String?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?>
}
