/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables


import co.spoonradio.sims.repository.postgresql.DefaultSchema
import co.spoonradio.sims.repository.postgresql.keys.REPORTS_TALKREPORT_PKEY
import co.spoonradio.sims.repository.postgresql.tables.records.ReportsTalkreportRecord

import java.time.LocalDate

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ReportsTalkreport(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ReportsTalkreportRecord>?,
    aliased: Table<ReportsTalkreportRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ReportsTalkreportRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>reports_talkreport</code>
         */
        val REPORTS_TALKREPORT = ReportsTalkreport()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ReportsTalkreportRecord> = ReportsTalkreportRecord::class.java

    /**
     * The column <code>reports_talkreport.id</code>.
     */
    val ID: TableField<ReportsTalkreportRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>reports_talkreport.reporter</code>.
     */
    val REPORTER: TableField<ReportsTalkreportRecord, String?> = createField(DSL.name("reporter"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>reports_talkreport.reported</code>.
     */
    val REPORTED: TableField<ReportsTalkreportRecord, LocalDate?> = createField(DSL.name("reported"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>reports_talkreport.talk</code>.
     */
    val TALK: TableField<ReportsTalkreportRecord, String?> = createField(DSL.name("talk"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>reports_talkreport.talk_author</code>.
     */
    val TALK_AUTHOR: TableField<ReportsTalkreportRecord, String?> = createField(DSL.name("talk_author"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>reports_talkreport.talk_created</code>.
     */
    val TALK_CREATED: TableField<ReportsTalkreportRecord, LocalDate?> = createField(DSL.name("talk_created"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>reports_talkreport.report_descr</code>.
     */
    val REPORT_DESCR: TableField<ReportsTalkreportRecord, String?> = createField(DSL.name("report_descr"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>reports_talkreport.report_type</code>.
     */
    val REPORT_TYPE: TableField<ReportsTalkreportRecord, Int?> = createField(DSL.name("report_type"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ReportsTalkreportRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ReportsTalkreportRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>reports_talkreport</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>reports_talkreport</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>reports_talkreport</code> table reference
     */
    constructor(): this(DSL.name("reports_talkreport"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ReportsTalkreportRecord>): this(Internal.createPathAlias(child, key), child, key, REPORTS_TALKREPORT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<ReportsTalkreportRecord, Int?> = super.getIdentity() as Identity<ReportsTalkreportRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<ReportsTalkreportRecord> = REPORTS_TALKREPORT_PKEY
    override fun getKeys(): List<UniqueKey<ReportsTalkreportRecord>> = listOf(REPORTS_TALKREPORT_PKEY)
    override fun `as`(alias: String): ReportsTalkreport = ReportsTalkreport(DSL.name(alias), this)
    override fun `as`(alias: Name): ReportsTalkreport = ReportsTalkreport(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ReportsTalkreport = ReportsTalkreport(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ReportsTalkreport = ReportsTalkreport(name, null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, Int?> = super.fieldsRow() as Row8<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, Int?>
}
