/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables


import co.spoonradio.sims.repository.postgresql.DefaultSchema
import co.spoonradio.sims.repository.postgresql.keys.REPORTS_CASTCOMMENTREPORT_PKEY
import co.spoonradio.sims.repository.postgresql.tables.records.ReportsCastcommentreportRecord

import java.time.LocalDate

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row11
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ReportsCastcommentreport(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ReportsCastcommentreportRecord>?,
    aliased: Table<ReportsCastcommentreportRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ReportsCastcommentreportRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>reports_castcommentreport</code>
         */
        val REPORTS_CASTCOMMENTREPORT = ReportsCastcommentreport()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ReportsCastcommentreportRecord> = ReportsCastcommentreportRecord::class.java

    /**
     * The column <code>reports_castcommentreport.id</code>.
     */
    val ID: TableField<ReportsCastcommentreportRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>reports_castcommentreport.reporter</code>.
     */
    val REPORTER: TableField<ReportsCastcommentreportRecord, String?> = createField(DSL.name("reporter"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.reported</code>.
     */
    val REPORTED: TableField<ReportsCastcommentreportRecord, LocalDate?> = createField(DSL.name("reported"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.cast</code>.
     */
    val CAST: TableField<ReportsCastcommentreportRecord, String?> = createField(DSL.name("cast"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.cast_author</code>.
     */
    val CAST_AUTHOR: TableField<ReportsCastcommentreportRecord, String?> = createField(DSL.name("cast_author"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.cast_created</code>.
     */
    val CAST_CREATED: TableField<ReportsCastcommentreportRecord, LocalDate?> = createField(DSL.name("cast_created"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.comment_author</code>.
     */
    val COMMENT_AUTHOR: TableField<ReportsCastcommentreportRecord, String?> = createField(DSL.name("comment_author"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.comment_contents</code>.
     */
    val COMMENT_CONTENTS: TableField<ReportsCastcommentreportRecord, String?> = createField(DSL.name("comment_contents"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.comment_created</code>.
     */
    val COMMENT_CREATED: TableField<ReportsCastcommentreportRecord, LocalDate?> = createField(DSL.name("comment_created"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>reports_castcommentreport.report_descr</code>.
     */
    val REPORT_DESCR: TableField<ReportsCastcommentreportRecord, String?> = createField(DSL.name("report_descr"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>reports_castcommentreport.report_type</code>.
     */
    val REPORT_TYPE: TableField<ReportsCastcommentreportRecord, Int?> = createField(DSL.name("report_type"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ReportsCastcommentreportRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ReportsCastcommentreportRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>reports_castcommentreport</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>reports_castcommentreport</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>reports_castcommentreport</code> table reference
     */
    constructor(): this(DSL.name("reports_castcommentreport"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ReportsCastcommentreportRecord>): this(Internal.createPathAlias(child, key), child, key, REPORTS_CASTCOMMENTREPORT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<ReportsCastcommentreportRecord, Int?> = super.getIdentity() as Identity<ReportsCastcommentreportRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<ReportsCastcommentreportRecord> = REPORTS_CASTCOMMENTREPORT_PKEY
    override fun getKeys(): List<UniqueKey<ReportsCastcommentreportRecord>> = listOf(REPORTS_CASTCOMMENTREPORT_PKEY)
    override fun `as`(alias: String): ReportsCastcommentreport = ReportsCastcommentreport(DSL.name(alias), this)
    override fun `as`(alias: Name): ReportsCastcommentreport = ReportsCastcommentreport(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ReportsCastcommentreport = ReportsCastcommentreport(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ReportsCastcommentreport = ReportsCastcommentreport(name, null)

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row11<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, LocalDate?, String?, Int?> = super.fieldsRow() as Row11<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, LocalDate?, String?, Int?>
}
