/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables


import co.spoonradio.sims.repository.postgresql.DefaultSchema
import co.spoonradio.sims.repository.postgresql.indexes.IDX_USERS_AUTHORTIERUSER_TIER_ID
import co.spoonradio.sims.repository.postgresql.keys.FK_USERS_AUTHORTIERUSER_TIER_ID
import co.spoonradio.sims.repository.postgresql.keys.PK_USERS_AUTHORTIERUSER
import co.spoonradio.sims.repository.postgresql.keys.UIDX_USERS_AUTHORTIERUSER_USER_ID
import co.spoonradio.sims.repository.postgresql.tables.records.UsersAuthortieruserRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersAuthortieruser(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UsersAuthortieruserRecord>?,
    aliased: Table<UsersAuthortieruserRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UsersAuthortieruserRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>users_authortieruser</code>
         */
        val USERS_AUTHORTIERUSER = UsersAuthortieruser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersAuthortieruserRecord> = UsersAuthortieruserRecord::class.java

    /**
     * The column <code>users_authortieruser.id</code>.
     */
    val ID: TableField<UsersAuthortieruserRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>users_authortieruser.created</code>.
     */
    val CREATED: TableField<UsersAuthortieruserRecord, OffsetDateTime?> = createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>users_authortieruser.tier_id</code>.
     */
    val TIER_ID: TableField<UsersAuthortieruserRecord, Int?> = createField(DSL.name("tier_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>users_authortieruser.user_id</code>.
     */
    val USER_ID: TableField<UsersAuthortieruserRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UsersAuthortieruserRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UsersAuthortieruserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>users_authortieruser</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>users_authortieruser</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>users_authortieruser</code> table reference
     */
    constructor(): this(DSL.name("users_authortieruser"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UsersAuthortieruserRecord>): this(Internal.createPathAlias(child, key), child, key, USERS_AUTHORTIERUSER, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_USERS_AUTHORTIERUSER_TIER_ID)
    override fun getIdentity(): Identity<UsersAuthortieruserRecord, Int?> = super.getIdentity() as Identity<UsersAuthortieruserRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UsersAuthortieruserRecord> = PK_USERS_AUTHORTIERUSER
    override fun getKeys(): List<UniqueKey<UsersAuthortieruserRecord>> = listOf(PK_USERS_AUTHORTIERUSER, UIDX_USERS_AUTHORTIERUSER_USER_ID)
    override fun getReferences(): List<ForeignKey<UsersAuthortieruserRecord, *>> = listOf(FK_USERS_AUTHORTIERUSER_TIER_ID)

    private lateinit var _usersAuthortier: UsersAuthortier
    fun usersAuthortier(): UsersAuthortier {
        if (!this::_usersAuthortier.isInitialized)
            _usersAuthortier = UsersAuthortier(this, FK_USERS_AUTHORTIERUSER_TIER_ID)

        return _usersAuthortier;
    }
    override fun `as`(alias: String): UsersAuthortieruser = UsersAuthortieruser(DSL.name(alias), this)
    override fun `as`(alias: Name): UsersAuthortieruser = UsersAuthortieruser(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UsersAuthortieruser = UsersAuthortieruser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UsersAuthortieruser = UsersAuthortieruser(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, OffsetDateTime?, Int?, Int?> = super.fieldsRow() as Row4<Int?, OffsetDateTime?, Int?, Int?>
}
