/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables


import co.spoonradio.sims.repository.postgresql.DefaultSchema
import co.spoonradio.sims.repository.postgresql.keys.USERS_FOLLOW_PKEY
import co.spoonradio.sims.repository.postgresql.tables.records.UsersFollowRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersFollow(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UsersFollowRecord>?,
    aliased: Table<UsersFollowRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UsersFollowRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>users_follow</code>
         */
        val USERS_FOLLOW = UsersFollow()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersFollowRecord> = UsersFollowRecord::class.java

    /**
     * The column <code>users_follow.id</code>.
     */
    val ID: TableField<UsersFollowRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>users_follow.push_level</code>.
     */
    val PUSH_LEVEL: TableField<UsersFollowRecord, Int?> = createField(DSL.name("push_level"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>users_follow.created</code>.
     */
    val CREATED: TableField<UsersFollowRecord, OffsetDateTime?> = createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>users_follow.from_user_id</code>.
     */
    val FROM_USER_ID: TableField<UsersFollowRecord, Int?> = createField(DSL.name("from_user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>users_follow.to_user_id</code>.
     */
    val TO_USER_ID: TableField<UsersFollowRecord, Int?> = createField(DSL.name("to_user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UsersFollowRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UsersFollowRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>users_follow</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>users_follow</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>users_follow</code> table reference
     */
    constructor(): this(DSL.name("users_follow"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UsersFollowRecord>): this(Internal.createPathAlias(child, key), child, key, USERS_FOLLOW, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<UsersFollowRecord, Int?> = super.getIdentity() as Identity<UsersFollowRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UsersFollowRecord> = USERS_FOLLOW_PKEY
    override fun getKeys(): List<UniqueKey<UsersFollowRecord>> = listOf(USERS_FOLLOW_PKEY)
    override fun `as`(alias: String): UsersFollow = UsersFollow(DSL.name(alias), this)
    override fun `as`(alias: Name): UsersFollow = UsersFollow(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UsersFollow = UsersFollow(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UsersFollow = UsersFollow(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Int?, Int?, OffsetDateTime?, Int?, Int?> = super.fieldsRow() as Row5<Int?, Int?, OffsetDateTime?, Int?, Int?>
}
