/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables


import co.spoonradio.sims.repository.postgresql.DefaultSchema
import co.spoonradio.sims.repository.postgresql.indexes.IDX_USERS_AUTHORTIER_NAME
import co.spoonradio.sims.repository.postgresql.keys.PK_USERS_AUTHORTIER
import co.spoonradio.sims.repository.postgresql.keys.UIDX_USERS_AUTHORTIER_NAME
import co.spoonradio.sims.repository.postgresql.keys.UIDX_USERS_AUTHORTIER_ORDER
import co.spoonradio.sims.repository.postgresql.tables.records.UsersAuthortierRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersAuthortier(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UsersAuthortierRecord>?,
    aliased: Table<UsersAuthortierRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UsersAuthortierRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>users_authortier</code>
         */
        val USERS_AUTHORTIER = UsersAuthortier()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersAuthortierRecord> = UsersAuthortierRecord::class.java

    /**
     * The column <code>users_authortier.id</code>.
     */
    val ID: TableField<UsersAuthortierRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>users_authortier.name</code>.
     */
    val NAME: TableField<UsersAuthortierRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>users_authortier.title</code>.
     */
    val TITLE: TableField<UsersAuthortierRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>users_authortier.order</code>.
     */
    val ORDER: TableField<UsersAuthortierRecord, Int?> = createField(DSL.name("order"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>users_authortier.is_used</code>.
     */
    val IS_USED: TableField<UsersAuthortierRecord, Boolean?> = createField(DSL.name("is_used"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>users_authortier.created</code>.
     */
    val CREATED: TableField<UsersAuthortierRecord, OffsetDateTime?> = createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UsersAuthortierRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UsersAuthortierRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>users_authortier</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>users_authortier</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>users_authortier</code> table reference
     */
    constructor(): this(DSL.name("users_authortier"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UsersAuthortierRecord>): this(Internal.createPathAlias(child, key), child, key, USERS_AUTHORTIER, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_USERS_AUTHORTIER_NAME)
    override fun getIdentity(): Identity<UsersAuthortierRecord, Int?> = super.getIdentity() as Identity<UsersAuthortierRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UsersAuthortierRecord> = PK_USERS_AUTHORTIER
    override fun getKeys(): List<UniqueKey<UsersAuthortierRecord>> = listOf(PK_USERS_AUTHORTIER, UIDX_USERS_AUTHORTIER_NAME, UIDX_USERS_AUTHORTIER_ORDER)
    override fun `as`(alias: String): UsersAuthortier = UsersAuthortier(DSL.name(alias), this)
    override fun `as`(alias: Name): UsersAuthortier = UsersAuthortier(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UsersAuthortier = UsersAuthortier(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UsersAuthortier = UsersAuthortier(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?> = super.fieldsRow() as Row6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?>
}
