/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_8
import co.spoonradio.sims.repository.mysql.tables.records.AuthGroupRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthGroup(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AuthGroupRecord>?,
    aliased: Table<AuthGroupRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AuthGroupRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>auth_group</code>
         */
        val AUTH_GROUP = AuthGroup()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthGroupRecord> = AuthGroupRecord::class.java

    /**
     * The column <code>auth_group.id</code>.
     */
    val ID: TableField<AuthGroupRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>auth_group.name</code>.
     */
    val NAME: TableField<AuthGroupRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(150).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AuthGroupRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AuthGroupRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>auth_group</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>auth_group</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>auth_group</code> table reference
     */
    constructor(): this(DSL.name("auth_group"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AuthGroupRecord>): this(Internal.createPathAlias(child, key), child, key, AUTH_GROUP, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<AuthGroupRecord, Int?> = super.getIdentity() as Identity<AuthGroupRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<AuthGroupRecord> = CONSTRAINT_8
    override fun getKeys(): List<UniqueKey<AuthGroupRecord>> = listOf(CONSTRAINT_8, co.spoonradio.sims.repository.mysql.keys.NAME)
    override fun `as`(alias: String): AuthGroup = AuthGroup(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthGroup = AuthGroup(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthGroup = AuthGroup(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthGroup = AuthGroup(name, null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>
}
