/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_B4
import co.spoonradio.sims.repository.mysql.tables.records.BatchLogDeailRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BatchLogDeail(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, BatchLogDeailRecord>?,
    aliased: Table<BatchLogDeailRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<BatchLogDeailRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>batch_log_deail</code>
         */
        val BATCH_LOG_DEAIL = BatchLogDeail()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BatchLogDeailRecord> = BatchLogDeailRecord::class.java

    /**
     * The column <code>batch_log_deail.batch_log_detail_id</code>.
     */
    val BATCH_LOG_DETAIL_ID: TableField<BatchLogDeailRecord, Int?> = createField(DSL.name("batch_log_detail_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>batch_log_deail.description</code>.
     */
    val DESCRIPTION: TableField<BatchLogDeailRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>batch_log_deail.user_id</code>.
     */
    val USER_ID: TableField<BatchLogDeailRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>batch_log_deail.result_cd</code>.
     */
    val RESULT_CD: TableField<BatchLogDeailRecord, Int?> = createField(DSL.name("result_cd"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>batch_log_deail.create_dt</code>.
     */
    val CREATE_DT: TableField<BatchLogDeailRecord, LocalDateTime?> = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>batch_log_deail.batch_log_id</code>.
     */
    val BATCH_LOG_ID: TableField<BatchLogDeailRecord, Int?> = createField(DSL.name("batch_log_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BatchLogDeailRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<BatchLogDeailRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>batch_log_deail</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>batch_log_deail</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>batch_log_deail</code> table reference
     */
    constructor(): this(DSL.name("batch_log_deail"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, BatchLogDeailRecord>): this(Internal.createPathAlias(child, key), child, key, BATCH_LOG_DEAIL, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<BatchLogDeailRecord, Int?> = super.getIdentity() as Identity<BatchLogDeailRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<BatchLogDeailRecord> = CONSTRAINT_B4
    override fun getKeys(): List<UniqueKey<BatchLogDeailRecord>> = listOf(CONSTRAINT_B4)
    override fun `as`(alias: String): BatchLogDeail = BatchLogDeail(DSL.name(alias), this)
    override fun `as`(alias: Name): BatchLogDeail = BatchLogDeail(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BatchLogDeail = BatchLogDeail(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BatchLogDeail = BatchLogDeail(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, String?, Int?, Int?, LocalDateTime?, Int?> = super.fieldsRow() as Row6<Int?, String?, Int?, Int?, LocalDateTime?, Int?>
}
