/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_C
import co.spoonradio.sims.repository.mysql.tables.records.BatchLogRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BatchLog(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, BatchLogRecord>?,
    aliased: Table<BatchLogRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<BatchLogRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>batch_log</code>
         */
        val BATCH_LOG = BatchLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BatchLogRecord> = BatchLogRecord::class.java

    /**
     * The column <code>batch_log.batch_log_id</code>.
     */
    val BATCH_LOG_ID: TableField<BatchLogRecord, Int?> = createField(DSL.name("batch_log_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>batch_log.batch_type_cd</code>.
     */
    val BATCH_TYPE_CD: TableField<BatchLogRecord, String?> = createField(DSL.name("batch_type_cd"), SQLDataType.VARCHAR(5).nullable(false), this, "")

    /**
     * The column <code>batch_log.batch_detail</code>.
     */
    val BATCH_DETAIL: TableField<BatchLogRecord, String?> = createField(DSL.name("batch_detail"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>batch_log.batch_parameter</code>.
     */
    val BATCH_PARAMETER: TableField<BatchLogRecord, String?> = createField(DSL.name("batch_parameter"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>batch_log.create_dt</code>.
     */
    val CREATE_DT: TableField<BatchLogRecord, LocalDateTime?> = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>batch_log.is_success</code>.
     */
    val IS_SUCCESS: TableField<BatchLogRecord, Byte?> = createField(DSL.name("is_success"), SQLDataType.TINYINT.nullable(false), this, "")

    /**
     * The column <code>batch_log.cnt</code>.
     */
    val CNT: TableField<BatchLogRecord, Int?> = createField(DSL.name("cnt"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<BatchLogRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<BatchLogRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>batch_log</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>batch_log</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>batch_log</code> table reference
     */
    constructor(): this(DSL.name("batch_log"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, BatchLogRecord>): this(Internal.createPathAlias(child, key), child, key, BATCH_LOG, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<BatchLogRecord, Int?> = super.getIdentity() as Identity<BatchLogRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<BatchLogRecord> = CONSTRAINT_C
    override fun getKeys(): List<UniqueKey<BatchLogRecord>> = listOf(CONSTRAINT_C)
    override fun `as`(alias: String): BatchLog = BatchLog(DSL.name(alias), this)
    override fun `as`(alias: Name): BatchLog = BatchLog(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BatchLog = BatchLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BatchLog = BatchLog(name, null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Int?, String?, String?, String?, LocalDateTime?, Byte?, Int?> = super.fieldsRow() as Row7<Int?, String?, String?, String?, LocalDateTime?, Byte?, Int?>
}
