/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_B3
import co.spoonradio.sims.repository.mysql.tables.records.DjangoAdminLogRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DjangoAdminLog(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DjangoAdminLogRecord>?,
    aliased: Table<DjangoAdminLogRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DjangoAdminLogRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>django_admin_log</code>
         */
        val DJANGO_ADMIN_LOG = DjangoAdminLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DjangoAdminLogRecord> = DjangoAdminLogRecord::class.java

    /**
     * The column <code>django_admin_log.id</code>.
     */
    val ID: TableField<DjangoAdminLogRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>django_admin_log.action_time</code>.
     */
    val ACTION_TIME: TableField<DjangoAdminLogRecord, LocalDateTime?> = createField(DSL.name("action_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>django_admin_log.object_id</code>.
     */
    val OBJECT_ID: TableField<DjangoAdminLogRecord, String?> = createField(DSL.name("object_id"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>django_admin_log.object_repr</code>.
     */
    val OBJECT_REPR: TableField<DjangoAdminLogRecord, String?> = createField(DSL.name("object_repr"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>django_admin_log.action_flag</code>.
     */
    val ACTION_FLAG: TableField<DjangoAdminLogRecord, Int?> = createField(DSL.name("action_flag"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>django_admin_log.change_message</code>.
     */
    val CHANGE_MESSAGE: TableField<DjangoAdminLogRecord, String?> = createField(DSL.name("change_message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>django_admin_log.content_type_id</code>.
     */
    val CONTENT_TYPE_ID: TableField<DjangoAdminLogRecord, Int?> = createField(DSL.name("content_type_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>django_admin_log.user_id</code>.
     */
    val USER_ID: TableField<DjangoAdminLogRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<DjangoAdminLogRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DjangoAdminLogRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>django_admin_log</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>django_admin_log</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>django_admin_log</code> table reference
     */
    constructor(): this(DSL.name("django_admin_log"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DjangoAdminLogRecord>): this(Internal.createPathAlias(child, key), child, key, DJANGO_ADMIN_LOG, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<DjangoAdminLogRecord, Int?> = super.getIdentity() as Identity<DjangoAdminLogRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<DjangoAdminLogRecord> = CONSTRAINT_B3
    override fun getKeys(): List<UniqueKey<DjangoAdminLogRecord>> = listOf(CONSTRAINT_B3)
    override fun `as`(alias: String): DjangoAdminLog = DjangoAdminLog(DSL.name(alias), this)
    override fun `as`(alias: Name): DjangoAdminLog = DjangoAdminLog(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DjangoAdminLog = DjangoAdminLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DjangoAdminLog = DjangoAdminLog(name, null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Int?, LocalDateTime?, String?, String?, Int?, String?, Int?, Int?> = super.fieldsRow() as Row8<Int?, LocalDateTime?, String?, String?, Int?, String?, Int?, Int?>
}
