/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_6
import co.spoonradio.sims.repository.mysql.tables.records.DjangoMigrationsRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DjangoMigrations(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DjangoMigrationsRecord>?,
    aliased: Table<DjangoMigrationsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DjangoMigrationsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>django_migrations</code>
         */
        val DJANGO_MIGRATIONS = DjangoMigrations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DjangoMigrationsRecord> = DjangoMigrationsRecord::class.java

    /**
     * The column <code>django_migrations.id</code>.
     */
    val ID: TableField<DjangoMigrationsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>django_migrations.app</code>.
     */
    val APP: TableField<DjangoMigrationsRecord, String?> = createField(DSL.name("app"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>django_migrations.name</code>.
     */
    val NAME: TableField<DjangoMigrationsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>django_migrations.applied</code>.
     */
    val APPLIED: TableField<DjangoMigrationsRecord, LocalDateTime?> = createField(DSL.name("applied"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<DjangoMigrationsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DjangoMigrationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>django_migrations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>django_migrations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>django_migrations</code> table reference
     */
    constructor(): this(DSL.name("django_migrations"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DjangoMigrationsRecord>): this(Internal.createPathAlias(child, key), child, key, DJANGO_MIGRATIONS, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<DjangoMigrationsRecord, Int?> = super.getIdentity() as Identity<DjangoMigrationsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<DjangoMigrationsRecord> = CONSTRAINT_6
    override fun getKeys(): List<UniqueKey<DjangoMigrationsRecord>> = listOf(CONSTRAINT_6)
    override fun `as`(alias: String): DjangoMigrations = DjangoMigrations(DSL.name(alias), this)
    override fun `as`(alias: Name): DjangoMigrations = DjangoMigrations(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DjangoMigrations = DjangoMigrations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DjangoMigrations = DjangoMigrations(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, String?, String?, LocalDateTime?> = super.fieldsRow() as Row4<Int?, String?, String?, LocalDateTime?>
}
