/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_33
import co.spoonradio.sims.repository.mysql.tables.records.MenuRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Menu(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, MenuRecord>?,
    aliased: Table<MenuRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<MenuRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>menu</code>
         */
        val MENU = Menu()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MenuRecord> = MenuRecord::class.java

    /**
     * The column <code>menu.menu_id</code>.
     */
    val MENU_ID: TableField<MenuRecord, Int?> = createField(DSL.name("menu_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>menu.name</code>.
     */
    val NAME: TableField<MenuRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>menu.en_name</code>.
     */
    val EN_NAME: TableField<MenuRecord, String?> = createField(DSL.name("en_name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>menu.ord</code>.
     */
    val ORD: TableField<MenuRecord, Int?> = createField(DSL.name("ord"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>menu.create_dt</code>.
     */
    val CREATE_DT: TableField<MenuRecord, LocalDateTime?> = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>menu.update_dt</code>.
     */
    val UPDATE_DT: TableField<MenuRecord, LocalDateTime?> = createField(DSL.name("update_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>menu.icon</code>.
     */
    val ICON: TableField<MenuRecord, String?> = createField(DSL.name("icon"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>menu.is_used</code>.
     */
    val IS_USED: TableField<MenuRecord, Byte?> = createField(DSL.name("is_used"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field("1", SQLDataType.TINYINT)), this, "")

    private constructor(alias: Name, aliased: Table<MenuRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<MenuRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>menu</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>menu</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>menu</code> table reference
     */
    constructor(): this(DSL.name("menu"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, MenuRecord>): this(Internal.createPathAlias(child, key), child, key, MENU, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<MenuRecord, Int?> = super.getIdentity() as Identity<MenuRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<MenuRecord> = CONSTRAINT_33
    override fun getKeys(): List<UniqueKey<MenuRecord>> = listOf(CONSTRAINT_33)
    override fun `as`(alias: String): Menu = Menu(DSL.name(alias), this)
    override fun `as`(alias: Name): Menu = Menu(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Menu = Menu(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Menu = Menu(name, null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, String?, Byte?> = super.fieldsRow() as Row8<Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, String?, Byte?>
}
