/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_6C
import co.spoonradio.sims.repository.mysql.tables.records.SpcAuthReqRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SpcAuthReq(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SpcAuthReqRecord>?,
    aliased: Table<SpcAuthReqRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SpcAuthReqRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>spc_auth_req</code>
         */
        val SPC_AUTH_REQ = SpcAuthReq()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SpcAuthReqRecord> = SpcAuthReqRecord::class.java

    /**
     * The column <code>spc_auth_req.spc_auth_req_id</code>.
     */
    val SPC_AUTH_REQ_ID: TableField<SpcAuthReqRecord, Int?> = createField(DSL.name("spc_auth_req_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>spc_auth_req.req_detail</code>.
     */
    val REQ_DETAIL: TableField<SpcAuthReqRecord, String?> = createField(DSL.name("req_detail"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.spc_auth_cd</code>.
     */
    val SPC_AUTH_CD: TableField<SpcAuthReqRecord, String?> = createField(DSL.name("spc_auth_cd"), SQLDataType.VARCHAR(5).nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.status_cd</code>.
     */
    val STATUS_CD: TableField<SpcAuthReqRecord, String?> = createField(DSL.name("status_cd"), SQLDataType.VARCHAR(5).nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.create_dt</code>.
     */
    val CREATE_DT: TableField<SpcAuthReqRecord, LocalDateTime?> = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.update_dt</code>.
     */
    val UPDATE_DT: TableField<SpcAuthReqRecord, LocalDateTime?> = createField(DSL.name("update_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.req_user_id</code>.
     */
    val REQ_USER_ID: TableField<SpcAuthReqRecord, Int?> = createField(DSL.name("req_user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.sub_menu_id</code>.
     */
    val SUB_MENU_ID: TableField<SpcAuthReqRecord, Int?> = createField(DSL.name("sub_menu_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>spc_auth_req.en_req_detail</code>.
     */
    val EN_REQ_DETAIL: TableField<SpcAuthReqRecord, String?> = createField(DSL.name("en_req_detail"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SpcAuthReqRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SpcAuthReqRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>spc_auth_req</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>spc_auth_req</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>spc_auth_req</code> table reference
     */
    constructor(): this(DSL.name("spc_auth_req"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SpcAuthReqRecord>): this(Internal.createPathAlias(child, key), child, key, SPC_AUTH_REQ, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<SpcAuthReqRecord, Int?> = super.getIdentity() as Identity<SpcAuthReqRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<SpcAuthReqRecord> = CONSTRAINT_6C
    override fun getKeys(): List<UniqueKey<SpcAuthReqRecord>> = listOf(CONSTRAINT_6C)
    override fun `as`(alias: String): SpcAuthReq = SpcAuthReq(DSL.name(alias), this)
    override fun `as`(alias: Name): SpcAuthReq = SpcAuthReq(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SpcAuthReq = SpcAuthReq(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SpcAuthReq = SpcAuthReq(name, null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?> = super.fieldsRow() as Row9<Int?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, String?>
}
