/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_F5
import co.spoonradio.sims.repository.mysql.tables.records.TbexchangeactionhistoryRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tbexchangeactionhistory(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TbexchangeactionhistoryRecord>?,
    aliased: Table<TbexchangeactionhistoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TbexchangeactionhistoryRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tbExchangeActionHistory</code>
         */
        val TBEXCHANGEACTIONHISTORY = Tbexchangeactionhistory()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TbexchangeactionhistoryRecord> = TbexchangeactionhistoryRecord::class.java

    /**
     * The column <code>tbExchangeActionHistory.id</code>.
     */
    val ID: TableField<TbexchangeactionhistoryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>tbExchangeActionHistory.txid</code>.
     */
    val TXID: TableField<TbexchangeactionhistoryRecord, String?> = createField(DSL.name("txid"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column <code>tbExchangeActionHistory.targetLockId</code>.
     */
    val TARGETLOCKID: TableField<TbexchangeactionhistoryRecord, String?> = createField(DSL.name("targetLockId"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column <code>tbExchangeActionHistory.type</code>.
     */
    val TYPE: TableField<TbexchangeactionhistoryRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(6).nullable(false), this, "")

    /**
     * The column <code>tbExchangeActionHistory.created</code>.
     */
    val CREATED: TableField<TbexchangeactionhistoryRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>tbExchangeActionHistory.creator</code>.
     */
    val CREATOR: TableField<TbexchangeactionhistoryRecord, Long?> = createField(DSL.name("creator"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TbexchangeactionhistoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TbexchangeactionhistoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tbExchangeActionHistory</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tbExchangeActionHistory</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tbExchangeActionHistory</code> table reference
     */
    constructor(): this(DSL.name("tbExchangeActionHistory"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TbexchangeactionhistoryRecord>): this(Internal.createPathAlias(child, key), child, key, TBEXCHANGEACTIONHISTORY, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TbexchangeactionhistoryRecord, Long?> = super.getIdentity() as Identity<TbexchangeactionhistoryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TbexchangeactionhistoryRecord> = CONSTRAINT_F5
    override fun getKeys(): List<UniqueKey<TbexchangeactionhistoryRecord>> = listOf(CONSTRAINT_F5)
    override fun `as`(alias: String): Tbexchangeactionhistory = Tbexchangeactionhistory(DSL.name(alias), this)
    override fun `as`(alias: Name): Tbexchangeactionhistory = Tbexchangeactionhistory(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tbexchangeactionhistory = Tbexchangeactionhistory(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tbexchangeactionhistory = Tbexchangeactionhistory(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Long?, String?, String?, String?, LocalDateTime?, Long?> = super.fieldsRow() as Row6<Long?, String?, String?, String?, LocalDateTime?, Long?>
}
