/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_50
import co.spoonradio.sims.repository.mysql.tables.records.TeamMenuAuthListRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamMenuAuthList(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TeamMenuAuthListRecord>?,
    aliased: Table<TeamMenuAuthListRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TeamMenuAuthListRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>team_menu_auth_list</code>
         */
        val TEAM_MENU_AUTH_LIST = TeamMenuAuthList()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeamMenuAuthListRecord> = TeamMenuAuthListRecord::class.java

    /**
     * The column <code>team_menu_auth_list.id</code>.
     */
    val ID: TableField<TeamMenuAuthListRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>team_menu_auth_list.user_grp_cd</code>.
     */
    val USER_GRP_CD: TableField<TeamMenuAuthListRecord, String?> = createField(DSL.name("user_grp_cd"), SQLDataType.VARCHAR(5).nullable(false), this, "")

    /**
     * The column <code>team_menu_auth_list.create_dt</code>.
     */
    val CREATE_DT: TableField<TeamMenuAuthListRecord, LocalDateTime?> = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>team_menu_auth_list.update_dt</code>.
     */
    val UPDATE_DT: TableField<TeamMenuAuthListRecord, LocalDateTime?> = createField(DSL.name("update_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>team_menu_auth_list.sub_menu_id</code>.
     */
    val SUB_MENU_ID: TableField<TeamMenuAuthListRecord, Int?> = createField(DSL.name("sub_menu_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TeamMenuAuthListRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TeamMenuAuthListRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>team_menu_auth_list</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>team_menu_auth_list</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>team_menu_auth_list</code> table reference
     */
    constructor(): this(DSL.name("team_menu_auth_list"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TeamMenuAuthListRecord>): this(Internal.createPathAlias(child, key), child, key, TEAM_MENU_AUTH_LIST, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TeamMenuAuthListRecord, Int?> = super.getIdentity() as Identity<TeamMenuAuthListRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TeamMenuAuthListRecord> = CONSTRAINT_50
    override fun getKeys(): List<UniqueKey<TeamMenuAuthListRecord>> = listOf(CONSTRAINT_50)
    override fun `as`(alias: String): TeamMenuAuthList = TeamMenuAuthList(DSL.name(alias), this)
    override fun `as`(alias: Name): TeamMenuAuthList = TeamMenuAuthList(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TeamMenuAuthList = TeamMenuAuthList(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TeamMenuAuthList = TeamMenuAuthList(name, null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Int?, String?, LocalDateTime?, LocalDateTime?, Int?> = super.fieldsRow() as Row5<Int?, String?, LocalDateTime?, LocalDateTime?, Int?>
}
