/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables


import co.spoonradio.sims.repository.mysql.DefaultSchema
import co.spoonradio.sims.repository.mysql.keys.CONSTRAINT_85
import co.spoonradio.sims.repository.mysql.tables.records.TermsCheckRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TermsCheck(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TermsCheckRecord>?,
    aliased: Table<TermsCheckRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TermsCheckRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>terms_check</code>
         */
        val TERMS_CHECK = TermsCheck()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TermsCheckRecord> = TermsCheckRecord::class.java

    /**
     * The column <code>terms_check.terms_check_id</code>.
     */
    val TERMS_CHECK_ID: TableField<TermsCheckRecord, Int?> = createField(DSL.name("terms_check_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>terms_check.user_id</code>.
     */
    val USER_ID: TableField<TermsCheckRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>terms_check.create_dt</code>.
     */
    val CREATE_DT: TableField<TermsCheckRecord, LocalDateTime?> = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>terms_check.terms_id</code>.
     */
    val TERMS_ID: TableField<TermsCheckRecord, Int?> = createField(DSL.name("terms_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TermsCheckRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TermsCheckRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>terms_check</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>terms_check</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>terms_check</code> table reference
     */
    constructor(): this(DSL.name("terms_check"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TermsCheckRecord>): this(Internal.createPathAlias(child, key), child, key, TERMS_CHECK, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<TermsCheckRecord, Int?> = super.getIdentity() as Identity<TermsCheckRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TermsCheckRecord> = CONSTRAINT_85
    override fun getKeys(): List<UniqueKey<TermsCheckRecord>> = listOf(CONSTRAINT_85)
    override fun `as`(alias: String): TermsCheck = TermsCheck(DSL.name(alias), this)
    override fun `as`(alias: Name): TermsCheck = TermsCheck(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TermsCheck = TermsCheck(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TermsCheck = TermsCheck(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, Int?, LocalDateTime?, Int?> = super.fieldsRow() as Row4<Int?, Int?, LocalDateTime?, Int?>
}
