/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.records


import co.spoonradio.sims.repository.billing.tables.Tbsettlebankhistory

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TbsettlebankhistoryRecord() : UpdatableRecordImpl<TbsettlebankhistoryRecord>(Tbsettlebankhistory.TBSETTLEBANKHISTORY) {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var useragent: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var status: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var vbankstatus: Int?
        set(value) = set(3, value)
        get() = get(3) as Int?

    var txid: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    var pstatecd: String?
        set(value) = set(5, value)
        get() = get(5) as String?

    var ptrno: String?
        set(value) = set(6, value)
        get() = get(6) as String?

    var ptype: String?
        set(value) = set(7, value)
        get() = get(7) as String?

    var pmid: String?
        set(value) = set(8, value)
        get() = get(8) as String?

    var poid: String?
        set(value) = set(9, value)
        get() = get(9) as String?

    var pmname: String?
        set(value) = set(10, value)
        get() = get(10) as String?

    var pename: String?
        set(value) = set(11, value)
        get() = get(11) as String?

    var pgoods: String?
        set(value) = set(12, value)
        get() = get(12) as String?

    var phash: String?
        set(value) = set(13, value)
        get() = get(13) as String?

    var pfncd1: String?
        set(value) = set(14, value)
        get() = get(14) as String?

    var pfncd2: String?
        set(value) = set(15, value)
        get() = get(15) as String?

    var pfnnm: String?
        set(value) = set(16, value)
        get() = get(16) as String?

    var pamt: String?
        set(value) = set(17, value)
        get() = get(17) as String?

    var pauthno: String?
        set(value) = set(18, value)
        get() = get(18) as String?

    var pauthdt: String?
        set(value) = set(19, value)
        get() = get(19) as String?

    var pnoti: String?
        set(value) = set(20, value)
        get() = get(20) as String?

    var prmesg1: String?
        set(value) = set(21, value)
        get() = get(21) as String?

    var prmesg2: String?
        set(value) = set(22, value)
        get() = get(22) as String?

    var refundname: String?
        set(value) = set(23, value)
        get() = get(23) as String?

    var refundaccount: String?
        set(value) = set(24, value)
        get() = get(24) as String?

    var refundbank: String?
        set(value) = set(25, value)
        get() = get(25) as String?

    var payduedate: LocalDateTime?
        set(value) = set(26, value)
        get() = get(26) as LocalDateTime?

    var created: LocalDateTime?
        set(value) = set(27, value)
        get() = get(27) as LocalDateTime?

    var productid: Int?
        set(value) = set(28, value)
        get() = get(28) as Int?

    var promotionid: Int?
        set(value) = set(29, value)
        get() = get(29) as Int?

    var userid: Int?
        set(value) = set(30, value)
        get() = get(30) as Int?

    var completed: LocalDateTime?
        set(value) = set(31, value)
        get() = get(31) as LocalDateTime?

    var quantity: Int?
        set(value) = set(32, value)
        get() = get(32) as Int?

    var updated: LocalDateTime?
        set(value) = set(33, value)
        get() = get(33) as LocalDateTime?

    var puname: String?
        set(value) = set(34, value)
        get() = get(34) as String?

    var pfncd3: String?
        set(value) = set(35, value)
        get() = get(35) as String?

    var pbname: String?
        set(value) = set(36, value)
        get() = get(36) as String?

    var pintmon: String?
        set(value) = set(37, value)
        get() = get(37) as String?

    var pemail: String?
        set(value) = set(38, value)
        get() = get(38) as String?

    var poname: String?
        set(value) = set(39, value)
        get() = get(39) as String?

    var ppayno: String?
        set(value) = set(40, value)
        get() = get(40) as String?

    var pmixpaytrno: String?
        set(value) = set(41, value)
        get() = get(41) as String?

    var pmixpayamt: String?
        set(value) = set(42, value)
        get() = get(42) as String?

    var ppayamt: String?
        set(value) = set(43, value)
        get() = get(43) as String?

    var pcashauthno: String?
        set(value) = set(44, value)
        get() = get(44) as String?

    var phashsha256: String?
        set(value) = set(45, value)
        get() = get(45) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised TbsettlebankhistoryRecord
     */
    constructor(id: Int? = null, useragent: String? = null, status: String? = null, vbankstatus: Int? = null, txid: String? = null, pstatecd: String? = null, ptrno: String? = null, ptype: String? = null, pmid: String? = null, poid: String? = null, pmname: String? = null, pename: String? = null, pgoods: String? = null, phash: String? = null, pfncd1: String? = null, pfncd2: String? = null, pfnnm: String? = null, pamt: String? = null, pauthno: String? = null, pauthdt: String? = null, pnoti: String? = null, prmesg1: String? = null, prmesg2: String? = null, refundname: String? = null, refundaccount: String? = null, refundbank: String? = null, payduedate: LocalDateTime? = null, created: LocalDateTime? = null, productid: Int? = null, promotionid: Int? = null, userid: Int? = null, completed: LocalDateTime? = null, quantity: Int? = null, updated: LocalDateTime? = null, puname: String? = null, pfncd3: String? = null, pbname: String? = null, pintmon: String? = null, pemail: String? = null, poname: String? = null, ppayno: String? = null, pmixpaytrno: String? = null, pmixpayamt: String? = null, ppayamt: String? = null, pcashauthno: String? = null, phashsha256: String? = null): this() {
        this.id = id
        this.useragent = useragent
        this.status = status
        this.vbankstatus = vbankstatus
        this.txid = txid
        this.pstatecd = pstatecd
        this.ptrno = ptrno
        this.ptype = ptype
        this.pmid = pmid
        this.poid = poid
        this.pmname = pmname
        this.pename = pename
        this.pgoods = pgoods
        this.phash = phash
        this.pfncd1 = pfncd1
        this.pfncd2 = pfncd2
        this.pfnnm = pfnnm
        this.pamt = pamt
        this.pauthno = pauthno
        this.pauthdt = pauthdt
        this.pnoti = pnoti
        this.prmesg1 = prmesg1
        this.prmesg2 = prmesg2
        this.refundname = refundname
        this.refundaccount = refundaccount
        this.refundbank = refundbank
        this.payduedate = payduedate
        this.created = created
        this.productid = productid
        this.promotionid = promotionid
        this.userid = userid
        this.completed = completed
        this.quantity = quantity
        this.updated = updated
        this.puname = puname
        this.pfncd3 = pfncd3
        this.pbname = pbname
        this.pintmon = pintmon
        this.pemail = pemail
        this.poname = poname
        this.ppayno = ppayno
        this.pmixpaytrno = pmixpaytrno
        this.pmixpayamt = pmixpayamt
        this.ppayamt = ppayamt
        this.pcashauthno = pcashauthno
        this.phashsha256 = phashsha256
    }
}
