/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing.tables.records


import co.spoonradio.sims.repository.billing.tables.Tbsoftbankhistory

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record21
import org.jooq.Row21
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TbsoftbankhistoryRecord() : UpdatableRecordImpl<TbsoftbankhistoryRecord>(Tbsoftbankhistory.TBSOFTBANKHISTORY), Record21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var status: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var txid: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var paymethod: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var orderid: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    var tax: Int?
        set(value) = set(5, value)
        get() = get(5) as Int?

    var paytype: Int?
        set(value) = set(6, value)
        get() = get(6) as Int?

    var limitsecond: Int?
        set(value) = set(7, value)
        get() = get(7) as Int?

    var spshashcode: String?
        set(value) = set(8, value)
        get() = get(8) as String?

    var useragent: String?
        set(value) = set(9, value)
        get() = get(9) as String?

    var errorcode: String?
        set(value) = set(10, value)
        get() = get(10) as String?

    var resresult: String?
        set(value) = set(11, value)
        get() = get(11) as String?

    var requestdate: String?
        set(value) = set(12, value)
        get() = get(12) as String?

    var completed: LocalDateTime?
        set(value) = set(13, value)
        get() = get(13) as LocalDateTime?

    var created: LocalDateTime?
        set(value) = set(14, value)
        get() = get(14) as LocalDateTime?

    var productid: Int?
        set(value) = set(15, value)
        get() = get(15) as Int?

    var promotionid: Int?
        set(value) = set(16, value)
        get() = get(16) as Int?

    var userid: Int?
        set(value) = set(17, value)
        get() = get(17) as Int?

    var amount: Int?
        set(value) = set(18, value)
        get() = get(18) as Int?

    var quantity: Int?
        set(value) = set(19, value)
        get() = get(19) as Int?

    var updated: LocalDateTime?
        set(value) = set(20, value)
        get() = get(20) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?> = super.fieldsRow() as Row21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?>
    override fun valuesRow(): Row21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?> = super.valuesRow() as Row21<Int?, String?, String?, String?, String?, Int?, Int?, Int?, String?, String?, String?, String?, String?, LocalDateTime?, LocalDateTime?, Int?, Int?, Int?, Int?, Int?, LocalDateTime?>
    override fun field1(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.ID
    override fun field2(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.STATUS
    override fun field3(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.TXID
    override fun field4(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.PAYMETHOD
    override fun field5(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.ORDERID
    override fun field6(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.TAX
    override fun field7(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.PAYTYPE
    override fun field8(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.LIMITSECOND
    override fun field9(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.SPSHASHCODE
    override fun field10(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.USERAGENT
    override fun field11(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.ERRORCODE
    override fun field12(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.RESRESULT
    override fun field13(): Field<String?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.REQUESTDATE
    override fun field14(): Field<LocalDateTime?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.COMPLETED
    override fun field15(): Field<LocalDateTime?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.CREATED
    override fun field16(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.PRODUCTID
    override fun field17(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.PROMOTIONID
    override fun field18(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.USERID
    override fun field19(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.AMOUNT
    override fun field20(): Field<Int?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.QUANTITY
    override fun field21(): Field<LocalDateTime?> = Tbsoftbankhistory.TBSOFTBANKHISTORY.UPDATED
    override fun component1(): Int? = id
    override fun component2(): String? = status
    override fun component3(): String? = txid
    override fun component4(): String? = paymethod
    override fun component5(): String? = orderid
    override fun component6(): Int? = tax
    override fun component7(): Int? = paytype
    override fun component8(): Int? = limitsecond
    override fun component9(): String? = spshashcode
    override fun component10(): String? = useragent
    override fun component11(): String? = errorcode
    override fun component12(): String? = resresult
    override fun component13(): String? = requestdate
    override fun component14(): LocalDateTime? = completed
    override fun component15(): LocalDateTime? = created
    override fun component16(): Int? = productid
    override fun component17(): Int? = promotionid
    override fun component18(): Int? = userid
    override fun component19(): Int? = amount
    override fun component20(): Int? = quantity
    override fun component21(): LocalDateTime? = updated
    override fun value1(): Int? = id
    override fun value2(): String? = status
    override fun value3(): String? = txid
    override fun value4(): String? = paymethod
    override fun value5(): String? = orderid
    override fun value6(): Int? = tax
    override fun value7(): Int? = paytype
    override fun value8(): Int? = limitsecond
    override fun value9(): String? = spshashcode
    override fun value10(): String? = useragent
    override fun value11(): String? = errorcode
    override fun value12(): String? = resresult
    override fun value13(): String? = requestdate
    override fun value14(): LocalDateTime? = completed
    override fun value15(): LocalDateTime? = created
    override fun value16(): Int? = productid
    override fun value17(): Int? = promotionid
    override fun value18(): Int? = userid
    override fun value19(): Int? = amount
    override fun value20(): Int? = quantity
    override fun value21(): LocalDateTime? = updated

    override fun value1(value: Int?): TbsoftbankhistoryRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): TbsoftbankhistoryRecord {
        this.status = value
        return this
    }

    override fun value3(value: String?): TbsoftbankhistoryRecord {
        this.txid = value
        return this
    }

    override fun value4(value: String?): TbsoftbankhistoryRecord {
        this.paymethod = value
        return this
    }

    override fun value5(value: String?): TbsoftbankhistoryRecord {
        this.orderid = value
        return this
    }

    override fun value6(value: Int?): TbsoftbankhistoryRecord {
        this.tax = value
        return this
    }

    override fun value7(value: Int?): TbsoftbankhistoryRecord {
        this.paytype = value
        return this
    }

    override fun value8(value: Int?): TbsoftbankhistoryRecord {
        this.limitsecond = value
        return this
    }

    override fun value9(value: String?): TbsoftbankhistoryRecord {
        this.spshashcode = value
        return this
    }

    override fun value10(value: String?): TbsoftbankhistoryRecord {
        this.useragent = value
        return this
    }

    override fun value11(value: String?): TbsoftbankhistoryRecord {
        this.errorcode = value
        return this
    }

    override fun value12(value: String?): TbsoftbankhistoryRecord {
        this.resresult = value
        return this
    }

    override fun value13(value: String?): TbsoftbankhistoryRecord {
        this.requestdate = value
        return this
    }

    override fun value14(value: LocalDateTime?): TbsoftbankhistoryRecord {
        this.completed = value
        return this
    }

    override fun value15(value: LocalDateTime?): TbsoftbankhistoryRecord {
        this.created = value
        return this
    }

    override fun value16(value: Int?): TbsoftbankhistoryRecord {
        this.productid = value
        return this
    }

    override fun value17(value: Int?): TbsoftbankhistoryRecord {
        this.promotionid = value
        return this
    }

    override fun value18(value: Int?): TbsoftbankhistoryRecord {
        this.userid = value
        return this
    }

    override fun value19(value: Int?): TbsoftbankhistoryRecord {
        this.amount = value
        return this
    }

    override fun value20(value: Int?): TbsoftbankhistoryRecord {
        this.quantity = value
        return this
    }

    override fun value21(value: LocalDateTime?): TbsoftbankhistoryRecord {
        this.updated = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?, value4: String?, value5: String?, value6: Int?, value7: Int?, value8: Int?, value9: String?, value10: String?, value11: String?, value12: String?, value13: String?, value14: LocalDateTime?, value15: LocalDateTime?, value16: Int?, value17: Int?, value18: Int?, value19: Int?, value20: Int?, value21: LocalDateTime?): TbsoftbankhistoryRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        this.value17(value17)
        this.value18(value18)
        this.value19(value19)
        this.value20(value20)
        this.value21(value21)
        return this
    }

    /**
     * Create a detached, initialised TbsoftbankhistoryRecord
     */
    constructor(id: Int? = null, status: String? = null, txid: String? = null, paymethod: String? = null, orderid: String? = null, tax: Int? = null, paytype: Int? = null, limitsecond: Int? = null, spshashcode: String? = null, useragent: String? = null, errorcode: String? = null, resresult: String? = null, requestdate: String? = null, completed: LocalDateTime? = null, created: LocalDateTime? = null, productid: Int? = null, promotionid: Int? = null, userid: Int? = null, amount: Int? = null, quantity: Int? = null, updated: LocalDateTime? = null): this() {
        this.id = id
        this.status = status
        this.txid = txid
        this.paymethod = paymethod
        this.orderid = orderid
        this.tax = tax
        this.paytype = paytype
        this.limitsecond = limitsecond
        this.spshashcode = spshashcode
        this.useragent = useragent
        this.errorcode = errorcode
        this.resresult = resresult
        this.requestdate = requestdate
        this.completed = completed
        this.created = created
        this.productid = productid
        this.promotionid = promotionid
        this.userid = userid
        this.amount = amount
        this.quantity = quantity
        this.updated = updated
    }
}
