/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime
import java.util.Arrays


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CastsCast(
    val id: Int? = null, 
    val title: String? = null, 
    val interest: Int? = null, 
    val tags: Array<Any?>? = null, 
    val imgKey: String? = null, 
    val imgUrl: String? = null, 
    val voiceKey: String? = null, 
    val voiceUrl: String? = null, 
    val duration: Double? = null, 
    val likeCount: Int? = null, 
    val playCount: Int? = null, 
    val playRealCount: Int? = null, 
    val voiceCommentCount: Int? = null, 
    val textCommentCount: Int? = null, 
    val reporters: Array<Any?>? = null, 
    val updated: OffsetDateTime? = null, 
    val created: OffsetDateTime? = null, 
    val authorId: Int? = null, 
    val companyId: Int? = null, 
    val blockUsers: Array<Any?>? = null, 
    val isDonated: Boolean? = null, 
    val spoonCount: Int? = null, 
    val status: Int? = null, 
    val type: Int? = null, 
    val category: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("CastsCast (")

        sb.append(id)
        sb.append(", ").append(title)
        sb.append(", ").append(interest)
        sb.append(", ").append(Arrays.toString(tags))
        sb.append(", ").append(imgKey)
        sb.append(", ").append(imgUrl)
        sb.append(", ").append(voiceKey)
        sb.append(", ").append(voiceUrl)
        sb.append(", ").append(duration)
        sb.append(", ").append(likeCount)
        sb.append(", ").append(playCount)
        sb.append(", ").append(playRealCount)
        sb.append(", ").append(voiceCommentCount)
        sb.append(", ").append(textCommentCount)
        sb.append(", ").append(Arrays.toString(reporters))
        sb.append(", ").append(updated)
        sb.append(", ").append(created)
        sb.append(", ").append(authorId)
        sb.append(", ").append(companyId)
        sb.append(", ").append(Arrays.toString(blockUsers))
        sb.append(", ").append(isDonated)
        sb.append(", ").append(spoonCount)
        sb.append(", ").append(status)
        sb.append(", ").append(type)
        sb.append(", ").append(category)

        sb.append(")")
        return sb.toString()
    }
}
