/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CommonsUnfitword(
    val id: Int? = null, 
    val word: String? = null, 
    val created: OffsetDateTime? = null, 
    val isUsed: Boolean? = null, 
    val toContents: Boolean? = null, 
    val toNickname: Boolean? = null, 
    val reword: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("CommonsUnfitword (")

        sb.append(id)
        sb.append(", ").append(word)
        sb.append(", ").append(created)
        sb.append(", ").append(isUsed)
        sb.append(", ").append(toContents)
        sb.append(", ").append(toNickname)
        sb.append(", ").append(reword)

        sb.append(")")
        return sb.toString()
    }
}
