/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.pojos


import java.io.Serializable
import java.time.LocalDate


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ReportsCastcommentreport(
    val id: Int? = null, 
    val reporter: String? = null, 
    val reported: LocalDate? = null, 
    val cast: String? = null, 
    val castAuthor: String? = null, 
    val castCreated: LocalDate? = null, 
    val commentAuthor: String? = null, 
    val commentContents: String? = null, 
    val commentCreated: LocalDate? = null, 
    val reportDescr: String? = null, 
    val reportType: Int? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("ReportsCastcommentreport (")

        sb.append(id)
        sb.append(", ").append(reporter)
        sb.append(", ").append(reported)
        sb.append(", ").append(cast)
        sb.append(", ").append(castAuthor)
        sb.append(", ").append(castCreated)
        sb.append(", ").append(commentAuthor)
        sb.append(", ").append(commentContents)
        sb.append(", ").append(commentCreated)
        sb.append(", ").append(reportDescr)
        sb.append(", ").append(reportType)

        sb.append(")")
        return sb.toString()
    }
}
