/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UsersBancategorysub(
    val id: Int? = null, 
    val name: String? = null, 
    val isUse: Boolean? = null, 
    val created: OffsetDateTime? = null, 
    val categoryMainId: Int? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("UsersBancategorysub (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(isUse)
        sb.append(", ").append(created)
        sb.append(", ").append(categoryMainId)

        sb.append(")")
        return sb.toString()
    }
}
