/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.records


import co.spoonradio.sims.repository.postgresql.tables.ReportsCastreport

import java.time.LocalDate

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ReportsCastreportRecord() : UpdatableRecordImpl<ReportsCastreportRecord>(ReportsCastreport.REPORTS_CASTREPORT), Record9<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, Int?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var reporter: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var reported: LocalDate?
        set(value) = set(2, value)
        get() = get(2) as LocalDate?

    var cast: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var castAuthor: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    var castCreated: LocalDate?
        set(value) = set(5, value)
        get() = get(5) as LocalDate?

    var castUrl: String?
        set(value) = set(6, value)
        get() = get(6) as String?

    var reportDescr: String?
        set(value) = set(7, value)
        get() = get(7) as String?

    var reportType: Int?
        set(value) = set(8, value)
        get() = get(8) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, Int?> = super.fieldsRow() as Row9<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, Int?>
    override fun valuesRow(): Row9<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, Int?> = super.valuesRow() as Row9<Int?, String?, LocalDate?, String?, String?, LocalDate?, String?, String?, Int?>
    override fun field1(): Field<Int?> = ReportsCastreport.REPORTS_CASTREPORT.ID
    override fun field2(): Field<String?> = ReportsCastreport.REPORTS_CASTREPORT.REPORTER
    override fun field3(): Field<LocalDate?> = ReportsCastreport.REPORTS_CASTREPORT.REPORTED
    override fun field4(): Field<String?> = ReportsCastreport.REPORTS_CASTREPORT.CAST
    override fun field5(): Field<String?> = ReportsCastreport.REPORTS_CASTREPORT.CAST_AUTHOR
    override fun field6(): Field<LocalDate?> = ReportsCastreport.REPORTS_CASTREPORT.CAST_CREATED
    override fun field7(): Field<String?> = ReportsCastreport.REPORTS_CASTREPORT.CAST_URL
    override fun field8(): Field<String?> = ReportsCastreport.REPORTS_CASTREPORT.REPORT_DESCR
    override fun field9(): Field<Int?> = ReportsCastreport.REPORTS_CASTREPORT.REPORT_TYPE
    override fun component1(): Int? = id
    override fun component2(): String? = reporter
    override fun component3(): LocalDate? = reported
    override fun component4(): String? = cast
    override fun component5(): String? = castAuthor
    override fun component6(): LocalDate? = castCreated
    override fun component7(): String? = castUrl
    override fun component8(): String? = reportDescr
    override fun component9(): Int? = reportType
    override fun value1(): Int? = id
    override fun value2(): String? = reporter
    override fun value3(): LocalDate? = reported
    override fun value4(): String? = cast
    override fun value5(): String? = castAuthor
    override fun value6(): LocalDate? = castCreated
    override fun value7(): String? = castUrl
    override fun value8(): String? = reportDescr
    override fun value9(): Int? = reportType

    override fun value1(value: Int?): ReportsCastreportRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): ReportsCastreportRecord {
        this.reporter = value
        return this
    }

    override fun value3(value: LocalDate?): ReportsCastreportRecord {
        this.reported = value
        return this
    }

    override fun value4(value: String?): ReportsCastreportRecord {
        this.cast = value
        return this
    }

    override fun value5(value: String?): ReportsCastreportRecord {
        this.castAuthor = value
        return this
    }

    override fun value6(value: LocalDate?): ReportsCastreportRecord {
        this.castCreated = value
        return this
    }

    override fun value7(value: String?): ReportsCastreportRecord {
        this.castUrl = value
        return this
    }

    override fun value8(value: String?): ReportsCastreportRecord {
        this.reportDescr = value
        return this
    }

    override fun value9(value: Int?): ReportsCastreportRecord {
        this.reportType = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDate?, value4: String?, value5: String?, value6: LocalDate?, value7: String?, value8: String?, value9: Int?): ReportsCastreportRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised ReportsCastreportRecord
     */
    constructor(id: Int? = null, reporter: String? = null, reported: LocalDate? = null, cast: String? = null, castAuthor: String? = null, castCreated: LocalDate? = null, castUrl: String? = null, reportDescr: String? = null, reportType: Int? = null): this() {
        this.id = id
        this.reporter = reporter
        this.reported = reported
        this.cast = cast
        this.castAuthor = castAuthor
        this.castCreated = castCreated
        this.castUrl = castUrl
        this.reportDescr = reportDescr
        this.reportType = reportType
    }
}
