/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.records


import co.spoonradio.sims.repository.postgresql.tables.ReportsUserreport

import java.time.LocalDate

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ReportsUserreportRecord() : UpdatableRecordImpl<ReportsUserreportRecord>(ReportsUserreport.REPORTS_USERREPORT), Record9<Int?, String?, LocalDate?, String?, String?, String?, String?, String?, Int?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var reporter: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var reported: LocalDate?
        set(value) = set(2, value)
        get() = get(2) as LocalDate?

    var abuser: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var abuserTag: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    var abuserSnsType: String?
        set(value) = set(5, value)
        get() = get(5) as String?

    var abuserSnsId: String?
        set(value) = set(6, value)
        get() = get(6) as String?

    var reportDescr: String?
        set(value) = set(7, value)
        get() = get(7) as String?

    var reportType: Int?
        set(value) = set(8, value)
        get() = get(8) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<Int?, String?, LocalDate?, String?, String?, String?, String?, String?, Int?> = super.fieldsRow() as Row9<Int?, String?, LocalDate?, String?, String?, String?, String?, String?, Int?>
    override fun valuesRow(): Row9<Int?, String?, LocalDate?, String?, String?, String?, String?, String?, Int?> = super.valuesRow() as Row9<Int?, String?, LocalDate?, String?, String?, String?, String?, String?, Int?>
    override fun field1(): Field<Int?> = ReportsUserreport.REPORTS_USERREPORT.ID
    override fun field2(): Field<String?> = ReportsUserreport.REPORTS_USERREPORT.REPORTER
    override fun field3(): Field<LocalDate?> = ReportsUserreport.REPORTS_USERREPORT.REPORTED
    override fun field4(): Field<String?> = ReportsUserreport.REPORTS_USERREPORT.ABUSER
    override fun field5(): Field<String?> = ReportsUserreport.REPORTS_USERREPORT.ABUSER_TAG
    override fun field6(): Field<String?> = ReportsUserreport.REPORTS_USERREPORT.ABUSER_SNS_TYPE
    override fun field7(): Field<String?> = ReportsUserreport.REPORTS_USERREPORT.ABUSER_SNS_ID
    override fun field8(): Field<String?> = ReportsUserreport.REPORTS_USERREPORT.REPORT_DESCR
    override fun field9(): Field<Int?> = ReportsUserreport.REPORTS_USERREPORT.REPORT_TYPE
    override fun component1(): Int? = id
    override fun component2(): String? = reporter
    override fun component3(): LocalDate? = reported
    override fun component4(): String? = abuser
    override fun component5(): String? = abuserTag
    override fun component6(): String? = abuserSnsType
    override fun component7(): String? = abuserSnsId
    override fun component8(): String? = reportDescr
    override fun component9(): Int? = reportType
    override fun value1(): Int? = id
    override fun value2(): String? = reporter
    override fun value3(): LocalDate? = reported
    override fun value4(): String? = abuser
    override fun value5(): String? = abuserTag
    override fun value6(): String? = abuserSnsType
    override fun value7(): String? = abuserSnsId
    override fun value8(): String? = reportDescr
    override fun value9(): Int? = reportType

    override fun value1(value: Int?): ReportsUserreportRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): ReportsUserreportRecord {
        this.reporter = value
        return this
    }

    override fun value3(value: LocalDate?): ReportsUserreportRecord {
        this.reported = value
        return this
    }

    override fun value4(value: String?): ReportsUserreportRecord {
        this.abuser = value
        return this
    }

    override fun value5(value: String?): ReportsUserreportRecord {
        this.abuserTag = value
        return this
    }

    override fun value6(value: String?): ReportsUserreportRecord {
        this.abuserSnsType = value
        return this
    }

    override fun value7(value: String?): ReportsUserreportRecord {
        this.abuserSnsId = value
        return this
    }

    override fun value8(value: String?): ReportsUserreportRecord {
        this.reportDescr = value
        return this
    }

    override fun value9(value: Int?): ReportsUserreportRecord {
        this.reportType = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDate?, value4: String?, value5: String?, value6: String?, value7: String?, value8: String?, value9: Int?): ReportsUserreportRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised ReportsUserreportRecord
     */
    constructor(id: Int? = null, reporter: String? = null, reported: LocalDate? = null, abuser: String? = null, abuserTag: String? = null, abuserSnsType: String? = null, abuserSnsId: String? = null, reportDescr: String? = null, reportType: Int? = null): this() {
        this.id = id
        this.reporter = reporter
        this.reported = reported
        this.abuser = abuser
        this.abuserTag = abuserTag
        this.abuserSnsType = abuserSnsType
        this.abuserSnsId = abuserSnsId
        this.reportDescr = reportDescr
        this.reportType = reportType
    }
}
