/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.records


import co.spoonradio.sims.repository.postgresql.tables.TalksTalkvoicecomment

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record11
import org.jooq.Row11
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TalksTalkvoicecommentRecord() : UpdatableRecordImpl<TalksTalkvoicecommentRecord>(TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT), Record11<Int?, String?, String?, Double?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?, Int?, Int?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var voiceKey: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var voiceUrl: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var duration: Double?
        set(value) = set(3, value)
        get() = get(3) as Double?

    var reporters: Array<Any?>?
        set(value) = set(4, value)
        get() = get(4) as Array<Any?>?

    var created: OffsetDateTime?
        set(value) = set(5, value)
        get() = get(5) as OffsetDateTime?

    var authorId: Int?
        set(value) = set(6, value)
        get() = get(6) as Int?

    var talkId: Int?
        set(value) = set(7, value)
        get() = get(7) as Int?

    var toUserId: Int?
        set(value) = set(8, value)
        get() = get(8) as Int?

    var likeCount: Int?
        set(value) = set(9, value)
        get() = get(9) as Int?

    var playCount: Int?
        set(value) = set(10, value)
        get() = get(10) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row11<Int?, String?, String?, Double?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row11<Int?, String?, String?, Double?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row11<Int?, String?, String?, Double?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?, Int?, Int?> = super.valuesRow() as Row11<Int?, String?, String?, Double?, Array<Any?>?, OffsetDateTime?, Int?, Int?, Int?, Int?, Int?>
    override fun field1(): Field<Int?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.ID
    override fun field2(): Field<String?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.VOICE_KEY
    override fun field3(): Field<String?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.VOICE_URL
    override fun field4(): Field<Double?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.DURATION
    override fun field5(): Field<Array<Any?>?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.REPORTERS
    override fun field6(): Field<OffsetDateTime?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.CREATED
    override fun field7(): Field<Int?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.AUTHOR_ID
    override fun field8(): Field<Int?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.TALK_ID
    override fun field9(): Field<Int?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.TO_USER_ID
    override fun field10(): Field<Int?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.LIKE_COUNT
    override fun field11(): Field<Int?> = TalksTalkvoicecomment.TALKS_TALKVOICECOMMENT.PLAY_COUNT
    override fun component1(): Int? = id
    override fun component2(): String? = voiceKey
    override fun component3(): String? = voiceUrl
    override fun component4(): Double? = duration
    override fun component5(): Array<Any?>? = reporters
    override fun component6(): OffsetDateTime? = created
    override fun component7(): Int? = authorId
    override fun component8(): Int? = talkId
    override fun component9(): Int? = toUserId
    override fun component10(): Int? = likeCount
    override fun component11(): Int? = playCount
    override fun value1(): Int? = id
    override fun value2(): String? = voiceKey
    override fun value3(): String? = voiceUrl
    override fun value4(): Double? = duration
    override fun value5(): Array<Any?>? = reporters
    override fun value6(): OffsetDateTime? = created
    override fun value7(): Int? = authorId
    override fun value8(): Int? = talkId
    override fun value9(): Int? = toUserId
    override fun value10(): Int? = likeCount
    override fun value11(): Int? = playCount

    override fun value1(value: Int?): TalksTalkvoicecommentRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): TalksTalkvoicecommentRecord {
        this.voiceKey = value
        return this
    }

    override fun value3(value: String?): TalksTalkvoicecommentRecord {
        this.voiceUrl = value
        return this
    }

    override fun value4(value: Double?): TalksTalkvoicecommentRecord {
        this.duration = value
        return this
    }

    override fun value5(value: Array<Any?>?): TalksTalkvoicecommentRecord {
        this.reporters = value
        return this
    }

    override fun value6(value: OffsetDateTime?): TalksTalkvoicecommentRecord {
        this.created = value
        return this
    }

    override fun value7(value: Int?): TalksTalkvoicecommentRecord {
        this.authorId = value
        return this
    }

    override fun value8(value: Int?): TalksTalkvoicecommentRecord {
        this.talkId = value
        return this
    }

    override fun value9(value: Int?): TalksTalkvoicecommentRecord {
        this.toUserId = value
        return this
    }

    override fun value10(value: Int?): TalksTalkvoicecommentRecord {
        this.likeCount = value
        return this
    }

    override fun value11(value: Int?): TalksTalkvoicecommentRecord {
        this.playCount = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?, value4: Double?, value5: Array<Any?>?, value6: OffsetDateTime?, value7: Int?, value8: Int?, value9: Int?, value10: Int?, value11: Int?): TalksTalkvoicecommentRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        return this
    }

    /**
     * Create a detached, initialised TalksTalkvoicecommentRecord
     */
    constructor(id: Int? = null, voiceKey: String? = null, voiceUrl: String? = null, duration: Double? = null, reporters: Array<Any?>? = null, created: OffsetDateTime? = null, authorId: Int? = null, talkId: Int? = null, toUserId: Int? = null, likeCount: Int? = null, playCount: Int? = null): this() {
        this.id = id
        this.voiceKey = voiceKey
        this.voiceUrl = voiceUrl
        this.duration = duration
        this.reporters = reporters
        this.created = created
        this.authorId = authorId
        this.talkId = talkId
        this.toUserId = toUserId
        this.likeCount = likeCount
        this.playCount = playCount
    }
}
