/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.records


import co.spoonradio.sims.repository.postgresql.tables.UsersSpoonuser

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record17
import org.jooq.Row17
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersSpoonuserRecord() : UpdatableRecordImpl<UsersSpoonuserRecord>(UsersSpoonuser.USERS_SPOONUSER), Record17<Int?, String?, OffsetDateTime?, Boolean?, String?, String?, String?, String?, Boolean?, Boolean?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, Int?, Boolean?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var password: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var lastLogin: OffsetDateTime?
        set(value) = set(2, value)
        get() = get(2) as OffsetDateTime?

    var isSuperuser: Boolean?
        set(value) = set(3, value)
        get() = get(3) as Boolean?

    var username: String?
        set(value) = set(4, value)
        get() = get(4) as String?

    var firstName: String?
        set(value) = set(5, value)
        get() = get(5) as String?

    var lastName: String?
        set(value) = set(6, value)
        get() = get(6) as String?

    var email: String?
        set(value) = set(7, value)
        get() = get(7) as String?

    var isStaff: Boolean?
        set(value) = set(8, value)
        get() = get(8) as Boolean?

    var isActive: Boolean?
        set(value) = set(9, value)
        get() = get(9) as Boolean?

    var dateJoined: OffsetDateTime?
        set(value) = set(10, value)
        get() = get(10) as OffsetDateTime?

    var companyId: Int?
        set(value) = set(11, value)
        get() = get(11) as Int?

    var budgetId: Int?
        set(value) = set(12, value)
        get() = get(12) as Int?

    var grantsId: Int?
        set(value) = set(13, value)
        get() = get(13) as Int?

    var leaved: OffsetDateTime?
        set(value) = set(14, value)
        get() = get(14) as OffsetDateTime?

    var status: Int?
        set(value) = set(15, value)
        get() = get(15) as Int?

    var isDormant: Boolean?
        set(value) = set(16, value)
        get() = get(16) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row17<Int?, String?, OffsetDateTime?, Boolean?, String?, String?, String?, String?, Boolean?, Boolean?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, Int?, Boolean?> = super.fieldsRow() as Row17<Int?, String?, OffsetDateTime?, Boolean?, String?, String?, String?, String?, Boolean?, Boolean?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, Int?, Boolean?>
    override fun valuesRow(): Row17<Int?, String?, OffsetDateTime?, Boolean?, String?, String?, String?, String?, Boolean?, Boolean?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, Int?, Boolean?> = super.valuesRow() as Row17<Int?, String?, OffsetDateTime?, Boolean?, String?, String?, String?, String?, Boolean?, Boolean?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, Int?, Boolean?>
    override fun field1(): Field<Int?> = UsersSpoonuser.USERS_SPOONUSER.ID
    override fun field2(): Field<String?> = UsersSpoonuser.USERS_SPOONUSER.PASSWORD
    override fun field3(): Field<OffsetDateTime?> = UsersSpoonuser.USERS_SPOONUSER.LAST_LOGIN
    override fun field4(): Field<Boolean?> = UsersSpoonuser.USERS_SPOONUSER.IS_SUPERUSER
    override fun field5(): Field<String?> = UsersSpoonuser.USERS_SPOONUSER.USERNAME
    override fun field6(): Field<String?> = UsersSpoonuser.USERS_SPOONUSER.FIRST_NAME
    override fun field7(): Field<String?> = UsersSpoonuser.USERS_SPOONUSER.LAST_NAME
    override fun field8(): Field<String?> = UsersSpoonuser.USERS_SPOONUSER.EMAIL
    override fun field9(): Field<Boolean?> = UsersSpoonuser.USERS_SPOONUSER.IS_STAFF
    override fun field10(): Field<Boolean?> = UsersSpoonuser.USERS_SPOONUSER.IS_ACTIVE
    override fun field11(): Field<OffsetDateTime?> = UsersSpoonuser.USERS_SPOONUSER.DATE_JOINED
    override fun field12(): Field<Int?> = UsersSpoonuser.USERS_SPOONUSER.COMPANY_ID
    override fun field13(): Field<Int?> = UsersSpoonuser.USERS_SPOONUSER.BUDGET_ID
    override fun field14(): Field<Int?> = UsersSpoonuser.USERS_SPOONUSER.GRANTS_ID
    override fun field15(): Field<OffsetDateTime?> = UsersSpoonuser.USERS_SPOONUSER.LEAVED
    override fun field16(): Field<Int?> = UsersSpoonuser.USERS_SPOONUSER.STATUS
    override fun field17(): Field<Boolean?> = UsersSpoonuser.USERS_SPOONUSER.IS_DORMANT
    override fun component1(): Int? = id
    override fun component2(): String? = password
    override fun component3(): OffsetDateTime? = lastLogin
    override fun component4(): Boolean? = isSuperuser
    override fun component5(): String? = username
    override fun component6(): String? = firstName
    override fun component7(): String? = lastName
    override fun component8(): String? = email
    override fun component9(): Boolean? = isStaff
    override fun component10(): Boolean? = isActive
    override fun component11(): OffsetDateTime? = dateJoined
    override fun component12(): Int? = companyId
    override fun component13(): Int? = budgetId
    override fun component14(): Int? = grantsId
    override fun component15(): OffsetDateTime? = leaved
    override fun component16(): Int? = status
    override fun component17(): Boolean? = isDormant
    override fun value1(): Int? = id
    override fun value2(): String? = password
    override fun value3(): OffsetDateTime? = lastLogin
    override fun value4(): Boolean? = isSuperuser
    override fun value5(): String? = username
    override fun value6(): String? = firstName
    override fun value7(): String? = lastName
    override fun value8(): String? = email
    override fun value9(): Boolean? = isStaff
    override fun value10(): Boolean? = isActive
    override fun value11(): OffsetDateTime? = dateJoined
    override fun value12(): Int? = companyId
    override fun value13(): Int? = budgetId
    override fun value14(): Int? = grantsId
    override fun value15(): OffsetDateTime? = leaved
    override fun value16(): Int? = status
    override fun value17(): Boolean? = isDormant

    override fun value1(value: Int?): UsersSpoonuserRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): UsersSpoonuserRecord {
        this.password = value
        return this
    }

    override fun value3(value: OffsetDateTime?): UsersSpoonuserRecord {
        this.lastLogin = value
        return this
    }

    override fun value4(value: Boolean?): UsersSpoonuserRecord {
        this.isSuperuser = value
        return this
    }

    override fun value5(value: String?): UsersSpoonuserRecord {
        this.username = value
        return this
    }

    override fun value6(value: String?): UsersSpoonuserRecord {
        this.firstName = value
        return this
    }

    override fun value7(value: String?): UsersSpoonuserRecord {
        this.lastName = value
        return this
    }

    override fun value8(value: String?): UsersSpoonuserRecord {
        this.email = value
        return this
    }

    override fun value9(value: Boolean?): UsersSpoonuserRecord {
        this.isStaff = value
        return this
    }

    override fun value10(value: Boolean?): UsersSpoonuserRecord {
        this.isActive = value
        return this
    }

    override fun value11(value: OffsetDateTime?): UsersSpoonuserRecord {
        this.dateJoined = value
        return this
    }

    override fun value12(value: Int?): UsersSpoonuserRecord {
        this.companyId = value
        return this
    }

    override fun value13(value: Int?): UsersSpoonuserRecord {
        this.budgetId = value
        return this
    }

    override fun value14(value: Int?): UsersSpoonuserRecord {
        this.grantsId = value
        return this
    }

    override fun value15(value: OffsetDateTime?): UsersSpoonuserRecord {
        this.leaved = value
        return this
    }

    override fun value16(value: Int?): UsersSpoonuserRecord {
        this.status = value
        return this
    }

    override fun value17(value: Boolean?): UsersSpoonuserRecord {
        this.isDormant = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: OffsetDateTime?, value4: Boolean?, value5: String?, value6: String?, value7: String?, value8: String?, value9: Boolean?, value10: Boolean?, value11: OffsetDateTime?, value12: Int?, value13: Int?, value14: Int?, value15: OffsetDateTime?, value16: Int?, value17: Boolean?): UsersSpoonuserRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        this.value17(value17)
        return this
    }

    /**
     * Create a detached, initialised UsersSpoonuserRecord
     */
    constructor(id: Int? = null, password: String? = null, lastLogin: OffsetDateTime? = null, isSuperuser: Boolean? = null, username: String? = null, firstName: String? = null, lastName: String? = null, email: String? = null, isStaff: Boolean? = null, isActive: Boolean? = null, dateJoined: OffsetDateTime? = null, companyId: Int? = null, budgetId: Int? = null, grantsId: Int? = null, leaved: OffsetDateTime? = null, status: Int? = null, isDormant: Boolean? = null): this() {
        this.id = id
        this.password = password
        this.lastLogin = lastLogin
        this.isSuperuser = isSuperuser
        this.username = username
        this.firstName = firstName
        this.lastName = lastName
        this.email = email
        this.isStaff = isStaff
        this.isActive = isActive
        this.dateJoined = dateJoined
        this.companyId = companyId
        this.budgetId = budgetId
        this.grantsId = grantsId
        this.leaved = leaved
        this.status = status
        this.isDormant = isDormant
    }
}
