/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.records


import co.spoonradio.sims.repository.postgresql.tables.UsersAuthortier

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersAuthortierRecord() : UpdatableRecordImpl<UsersAuthortierRecord>(UsersAuthortier.USERS_AUTHORTIER), Record6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var name: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var title: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var order: Int?
        set(value) = set(3, value)
        get() = get(3) as Int?

    var isUsed: Boolean?
        set(value) = set(4, value)
        get() = get(4) as Boolean?

    var created: OffsetDateTime?
        set(value) = set(5, value)
        get() = get(5) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?> = super.fieldsRow() as Row6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?>
    override fun valuesRow(): Row6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?> = super.valuesRow() as Row6<Int?, String?, String?, Int?, Boolean?, OffsetDateTime?>
    override fun field1(): Field<Int?> = UsersAuthortier.USERS_AUTHORTIER.ID
    override fun field2(): Field<String?> = UsersAuthortier.USERS_AUTHORTIER.NAME
    override fun field3(): Field<String?> = UsersAuthortier.USERS_AUTHORTIER.TITLE
    override fun field4(): Field<Int?> = UsersAuthortier.USERS_AUTHORTIER.ORDER
    override fun field5(): Field<Boolean?> = UsersAuthortier.USERS_AUTHORTIER.IS_USED
    override fun field6(): Field<OffsetDateTime?> = UsersAuthortier.USERS_AUTHORTIER.CREATED
    override fun component1(): Int? = id
    override fun component2(): String? = name
    override fun component3(): String? = title
    override fun component4(): Int? = order
    override fun component5(): Boolean? = isUsed
    override fun component6(): OffsetDateTime? = created
    override fun value1(): Int? = id
    override fun value2(): String? = name
    override fun value3(): String? = title
    override fun value4(): Int? = order
    override fun value5(): Boolean? = isUsed
    override fun value6(): OffsetDateTime? = created

    override fun value1(value: Int?): UsersAuthortierRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): UsersAuthortierRecord {
        this.name = value
        return this
    }

    override fun value3(value: String?): UsersAuthortierRecord {
        this.title = value
        return this
    }

    override fun value4(value: Int?): UsersAuthortierRecord {
        this.order = value
        return this
    }

    override fun value5(value: Boolean?): UsersAuthortierRecord {
        this.isUsed = value
        return this
    }

    override fun value6(value: OffsetDateTime?): UsersAuthortierRecord {
        this.created = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?, value4: Int?, value5: Boolean?, value6: OffsetDateTime?): UsersAuthortierRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised UsersAuthortierRecord
     */
    constructor(id: Int? = null, name: String? = null, title: String? = null, order: Int? = null, isUsed: Boolean? = null, created: OffsetDateTime? = null): this() {
        this.id = id
        this.name = name
        this.title = title
        this.order = order
        this.isUsed = isUsed
        this.created = created
    }
}
