/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.tables.records


import co.spoonradio.sims.repository.postgresql.tables.UsersBancategorysub

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersBancategorysubRecord() : UpdatableRecordImpl<UsersBancategorysubRecord>(UsersBancategorysub.USERS_BANCATEGORYSUB), Record5<Int?, String?, Boolean?, OffsetDateTime?, Int?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var name: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var isUse: Boolean?
        set(value) = set(2, value)
        get() = get(2) as Boolean?

    var created: OffsetDateTime?
        set(value) = set(3, value)
        get() = get(3) as OffsetDateTime?

    var categoryMainId: Int?
        set(value) = set(4, value)
        get() = get(4) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Int?, String?, Boolean?, OffsetDateTime?, Int?> = super.fieldsRow() as Row5<Int?, String?, Boolean?, OffsetDateTime?, Int?>
    override fun valuesRow(): Row5<Int?, String?, Boolean?, OffsetDateTime?, Int?> = super.valuesRow() as Row5<Int?, String?, Boolean?, OffsetDateTime?, Int?>
    override fun field1(): Field<Int?> = UsersBancategorysub.USERS_BANCATEGORYSUB.ID
    override fun field2(): Field<String?> = UsersBancategorysub.USERS_BANCATEGORYSUB.NAME
    override fun field3(): Field<Boolean?> = UsersBancategorysub.USERS_BANCATEGORYSUB.IS_USE
    override fun field4(): Field<OffsetDateTime?> = UsersBancategorysub.USERS_BANCATEGORYSUB.CREATED
    override fun field5(): Field<Int?> = UsersBancategorysub.USERS_BANCATEGORYSUB.CATEGORY_MAIN_ID
    override fun component1(): Int? = id
    override fun component2(): String? = name
    override fun component3(): Boolean? = isUse
    override fun component4(): OffsetDateTime? = created
    override fun component5(): Int? = categoryMainId
    override fun value1(): Int? = id
    override fun value2(): String? = name
    override fun value3(): Boolean? = isUse
    override fun value4(): OffsetDateTime? = created
    override fun value5(): Int? = categoryMainId

    override fun value1(value: Int?): UsersBancategorysubRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): UsersBancategorysubRecord {
        this.name = value
        return this
    }

    override fun value3(value: Boolean?): UsersBancategorysubRecord {
        this.isUse = value
        return this
    }

    override fun value4(value: OffsetDateTime?): UsersBancategorysubRecord {
        this.created = value
        return this
    }

    override fun value5(value: Int?): UsersBancategorysubRecord {
        this.categoryMainId = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: Boolean?, value4: OffsetDateTime?, value5: Int?): UsersBancategorysubRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised UsersBancategorysubRecord
     */
    constructor(id: Int? = null, name: String? = null, isUse: Boolean? = null, created: OffsetDateTime? = null, categoryMainId: Int? = null): this() {
        this.id = id
        this.name = name
        this.isUse = isUse
        this.created = created
        this.categoryMainId = categoryMainId
    }
}
