/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.postgresql.indexes


import co.spoonradio.sims.repository.postgresql.tables.UsersAuthortier
import co.spoonradio.sims.repository.postgresql.tables.UsersAuthortieruser

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_USERS_AUTHORTIER_NAME: Index = Internal.createIndex(DSL.name("idx_users_authortier_name"), UsersAuthortier.USERS_AUTHORTIER, arrayOf(UsersAuthortier.USERS_AUTHORTIER.NAME), false)
val IDX_USERS_AUTHORTIERUSER_TIER_ID: Index = Internal.createIndex(DSL.name("idx_users_authortieruser_tier_id"), UsersAuthortieruser.USERS_AUTHORTIERUSER, arrayOf(UsersAuthortieruser.USERS_AUTHORTIERUSER.TIER_ID), false)
