/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ComCode(
    val id: Int? = null, 
    val grpCodeCd: String? = null, 
    val grpCodeName: String? = null, 
    val codeCd: String? = null, 
    val codeNm: String? = null, 
    val codeDesc: String? = null, 
    val etc1: String? = null, 
    val etc2: String? = null, 
    val etc3: String? = null, 
    val parentGrpCodeCd: String? = null, 
    val parentCodeCd: String? = null, 
    val useYn: Byte? = null, 
    val ord: Int? = null, 
    val updateDt: LocalDateTime? = null, 
    val createDt: LocalDateTime? = null, 
    val enCodeNm: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("ComCode (")

        sb.append(id)
        sb.append(", ").append(grpCodeCd)
        sb.append(", ").append(grpCodeName)
        sb.append(", ").append(codeCd)
        sb.append(", ").append(codeNm)
        sb.append(", ").append(codeDesc)
        sb.append(", ").append(etc1)
        sb.append(", ").append(etc2)
        sb.append(", ").append(etc3)
        sb.append(", ").append(parentGrpCodeCd)
        sb.append(", ").append(parentCodeCd)
        sb.append(", ").append(useYn)
        sb.append(", ").append(ord)
        sb.append(", ").append(updateDt)
        sb.append(", ").append(createDt)
        sb.append(", ").append(enCodeNm)

        sb.append(")")
        return sb.toString()
    }
}
