/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class DjangoMigrations(
    val id: Int? = null, 
    val app: String? = null, 
    val name: String? = null, 
    val applied: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("DjangoMigrations (")

        sb.append(id)
        sb.append(", ").append(app)
        sb.append(", ").append(name)
        sb.append(", ").append(applied)

        sb.append(")")
        return sb.toString()
    }
}
