/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ExternalLinkLog(
    val externalLinkLogId: Int? = null, 
    val billingId: Int? = null, 
    val externalLinkTypeCd: String? = null, 
    val externalLinkDetail: String? = null, 
    val externalLinkParameter: String? = null, 
    val resultCd: Int? = null, 
    val externalLinkResponse: String? = null, 
    val createDt: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("ExternalLinkLog (")

        sb.append(externalLinkLogId)
        sb.append(", ").append(billingId)
        sb.append(", ").append(externalLinkTypeCd)
        sb.append(", ").append(externalLinkDetail)
        sb.append(", ").append(externalLinkParameter)
        sb.append(", ").append(resultCd)
        sb.append(", ").append(externalLinkResponse)
        sb.append(", ").append(createDt)

        sb.append(")")
        return sb.toString()
    }
}
