/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SpcAuthReq(
    val spcAuthReqId: Int? = null, 
    val reqDetail: String? = null, 
    val spcAuthCd: String? = null, 
    val statusCd: String? = null, 
    val createDt: LocalDateTime? = null, 
    val updateDt: LocalDateTime? = null, 
    val reqUserId: Int? = null, 
    val subMenuId: Int? = null, 
    val enReqDetail: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("SpcAuthReq (")

        sb.append(spcAuthReqId)
        sb.append(", ").append(reqDetail)
        sb.append(", ").append(spcAuthCd)
        sb.append(", ").append(statusCd)
        sb.append(", ").append(createDt)
        sb.append(", ").append(updateDt)
        sb.append(", ").append(reqUserId)
        sb.append(", ").append(subMenuId)
        sb.append(", ").append(enReqDetail)

        sb.append(")")
        return sb.toString()
    }
}
