/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SpcAuthReqInfo(
    val spcAuthApproveId: Int? = null, 
    val ord: Int? = null, 
    val statusCd: String? = null, 
    val createDt: LocalDateTime? = null, 
    val updateDt: LocalDateTime? = null, 
    val approveUserId: Int? = null, 
    val spcAuthReqId: Int? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("SpcAuthReqInfo (")

        sb.append(spcAuthApproveId)
        sb.append(", ").append(ord)
        sb.append(", ").append(statusCd)
        sb.append(", ").append(createDt)
        sb.append(", ").append(updateDt)
        sb.append(", ").append(approveUserId)
        sb.append(", ").append(spcAuthReqId)

        sb.append(")")
        return sb.toString()
    }
}
