/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SpoonRewardUser(
    val id: Int? = null, 
    val userId: Long? = null, 
    val txId: String? = null, 
    val status: String? = null, 
    val created: LocalDateTime? = null, 
    val creator: Long? = null, 
    val updated: LocalDateTime? = null, 
    val updater: Long? = null, 
    val rewardId: Int? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("SpoonRewardUser (")

        sb.append(id)
        sb.append(", ").append(userId)
        sb.append(", ").append(txId)
        sb.append(", ").append(status)
        sb.append(", ").append(created)
        sb.append(", ").append(creator)
        sb.append(", ").append(updated)
        sb.append(", ").append(updater)
        sb.append(", ").append(rewardId)

        sb.append(")")
        return sb.toString()
    }
}
