/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SubMenu(
    val subMenuId: Int? = null, 
    val name: String? = null, 
    val enName: String? = null, 
    val ord: Int? = null, 
    val api: String? = null, 
    val apiMethod: String? = null, 
    val apiDetail: String? = null, 
    val menuTypeCd: String? = null, 
    val spcAuth: Byte? = null, 
    val spcAuthCd: String? = null, 
    val createDt: LocalDateTime? = null, 
    val updateDt: LocalDateTime? = null, 
    val menuId: Int? = null, 
    val isCommon: Byte? = null, 
    val isNs: Byte? = null, 
    val menuAuthTypeCd: String? = null, 
    val parentSubMenuId: Int? = null, 
    val enApiDetail: String? = null, 
    val parentTabMenuId: Short? = null, 
    val countryFlag: Short? = null, 
    val isUsed: Byte? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("SubMenu (")

        sb.append(subMenuId)
        sb.append(", ").append(name)
        sb.append(", ").append(enName)
        sb.append(", ").append(ord)
        sb.append(", ").append(api)
        sb.append(", ").append(apiMethod)
        sb.append(", ").append(apiDetail)
        sb.append(", ").append(menuTypeCd)
        sb.append(", ").append(spcAuth)
        sb.append(", ").append(spcAuthCd)
        sb.append(", ").append(createDt)
        sb.append(", ").append(updateDt)
        sb.append(", ").append(menuId)
        sb.append(", ").append(isCommon)
        sb.append(", ").append(isNs)
        sb.append(", ").append(menuAuthTypeCd)
        sb.append(", ").append(parentSubMenuId)
        sb.append(", ").append(enApiDetail)
        sb.append(", ").append(parentTabMenuId)
        sb.append(", ").append(countryFlag)
        sb.append(", ").append(isUsed)

        sb.append(")")
        return sb.toString()
    }
}
