/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.mysql.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UserMenuAuth(
    val userMenuAuthId: Int? = null, 
    val unmasking: Byte? = null, 
    val createDt: LocalDateTime? = null, 
    val updateDt: LocalDateTime? = null, 
    val subMenuId: Int? = null, 
    val userId: Int? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("UserMenuAuth (")

        sb.append(userMenuAuthId)
        sb.append(", ").append(unmasking)
        sb.append(", ").append(createDt)
        sb.append(", ").append(updateDt)
        sb.append(", ").append(subMenuId)
        sb.append(", ").append(userId)

        sb.append(")")
        return sb.toString()
    }
}
