/*
 * This file is generated by jOOQ.
 */
package co.spoonradio.sims.repository.billing


import co.spoonradio.sims.repository.billing.tables.Tbadpopcornhistory
import co.spoonradio.sims.repository.billing.tables.Tbapplestorehistory
import co.spoonradio.sims.repository.billing.tables.Tberrorlog
import co.spoonradio.sims.repository.billing.tables.Tbexchange
import co.spoonradio.sims.repository.billing.tables.Tbexchangeamount
import co.spoonradio.sims.repository.billing.tables.Tbexchangeamountdotmoneyhistory
import co.spoonradio.sims.repository.billing.tables.Tbexchangedeposit
import co.spoonradio.sims.repository.billing.tables.Tbexchangedotmoneyproducts
import co.spoonradio.sims.repository.billing.tables.Tbexchangedotmoneysignaturedata
import co.spoonradio.sims.repository.billing.tables.Tbexchangehistory
import co.spoonradio.sims.repository.billing.tables.Tbexchangerejectreason
import co.spoonradio.sims.repository.billing.tables.Tbexchangesubmitdocument
import co.spoonradio.sims.repository.billing.tables.Tbgiftcardhistory
import co.spoonradio.sims.repository.billing.tables.Tbitemproduct
import co.spoonradio.sims.repository.billing.tables.Tbitempromotion
import co.spoonradio.sims.repository.billing.tables.Tbitemstore
import co.spoonradio.sims.repository.billing.tables.Tbpayment
import co.spoonradio.sims.repository.billing.tables.Tbpaymentmethod
import co.spoonradio.sims.repository.billing.tables.Tbpaypalhistory
import co.spoonradio.sims.repository.billing.tables.Tbplaystorehistory
import co.spoonradio.sims.repository.billing.tables.Tbpromotionhistory
import co.spoonradio.sims.repository.billing.tables.Tbsettlebankhistory
import co.spoonradio.sims.repository.billing.tables.Tbsoftbankhistory
import co.spoonradio.sims.repository.billing.tables.Tbsubscribe
import co.spoonradio.sims.repository.billing.tables.Tbsubscribeandroidhistory
import co.spoonradio.sims.repository.billing.tables.Tbsubscribeioshistory
import co.spoonradio.sims.repository.billing.tables.Tbtosshistory
import co.spoonradio.sims.repository.billing.tables.Tbwebmoneyhistory

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA = DefaultSchema()
    }

    /**
     * The table <code>tbAdpopcornHistory</code>.
     */
    val TBADPOPCORNHISTORY get() = Tbadpopcornhistory.TBADPOPCORNHISTORY

    /**
     * The table <code>tbApplestoreHistory</code>.
     */
    val TBAPPLESTOREHISTORY get() = Tbapplestorehistory.TBAPPLESTOREHISTORY

    /**
     * The table <code>tbErrorLog</code>.
     */
    val TBERRORLOG get() = Tberrorlog.TBERRORLOG

    /**
     * The table <code>tbExchange</code>.
     */
    val TBEXCHANGE get() = Tbexchange.TBEXCHANGE

    /**
     * The table <code>tbExchangeAmount</code>.
     */
    val TBEXCHANGEAMOUNT get() = Tbexchangeamount.TBEXCHANGEAMOUNT

    /**
     * The table <code>tbExchangeAmountDotmoneyHistory</code>.
     */
    val TBEXCHANGEAMOUNTDOTMONEYHISTORY get() = Tbexchangeamountdotmoneyhistory.TBEXCHANGEAMOUNTDOTMONEYHISTORY

    /**
     * The table <code>tbExchangeDeposit</code>.
     */
    val TBEXCHANGEDEPOSIT get() = Tbexchangedeposit.TBEXCHANGEDEPOSIT

    /**
     * The table <code>tbExchangeDotmoneyProducts</code>.
     */
    val TBEXCHANGEDOTMONEYPRODUCTS get() = Tbexchangedotmoneyproducts.TBEXCHANGEDOTMONEYPRODUCTS

    /**
     * The table <code>tbExchangeDotmoneySignatureData</code>.
     */
    val TBEXCHANGEDOTMONEYSIGNATUREDATA get() = Tbexchangedotmoneysignaturedata.TBEXCHANGEDOTMONEYSIGNATUREDATA

    /**
     * The table <code>tbExchangeHistory</code>.
     */
    val TBEXCHANGEHISTORY get() = Tbexchangehistory.TBEXCHANGEHISTORY

    /**
     * The table <code>tbExchangeRejectReason</code>.
     */
    val TBEXCHANGEREJECTREASON get() = Tbexchangerejectreason.TBEXCHANGEREJECTREASON

    /**
     * The table <code>tbExchangeSubmitDocument</code>.
     */
    val TBEXCHANGESUBMITDOCUMENT get() = Tbexchangesubmitdocument.TBEXCHANGESUBMITDOCUMENT

    /**
     * The table <code>tbGiftcardHistory</code>.
     */
    val TBGIFTCARDHISTORY get() = Tbgiftcardhistory.TBGIFTCARDHISTORY

    /**
     * The table <code>tbItemProduct</code>.
     */
    val TBITEMPRODUCT get() = Tbitemproduct.TBITEMPRODUCT

    /**
     * The table <code>tbItemPromotion</code>.
     */
    val TBITEMPROMOTION get() = Tbitempromotion.TBITEMPROMOTION

    /**
     * The table <code>tbItemStore</code>.
     */
    val TBITEMSTORE get() = Tbitemstore.TBITEMSTORE

    /**
     * The table <code>tbPayment</code>.
     */
    val TBPAYMENT get() = Tbpayment.TBPAYMENT

    /**
     * The table <code>tbPaymentMethod</code>.
     */
    val TBPAYMENTMETHOD get() = Tbpaymentmethod.TBPAYMENTMETHOD

    /**
     * The table <code>tbPaypalHistory</code>.
     */
    val TBPAYPALHISTORY get() = Tbpaypalhistory.TBPAYPALHISTORY

    /**
     * The table <code>tbPlaystoreHistory</code>.
     */
    val TBPLAYSTOREHISTORY get() = Tbplaystorehistory.TBPLAYSTOREHISTORY

    /**
     * The table <code>tbPromotionHistory</code>.
     */
    val TBPROMOTIONHISTORY get() = Tbpromotionhistory.TBPROMOTIONHISTORY

    /**
     * The table <code>tbSettleBankHistory</code>.
     */
    val TBSETTLEBANKHISTORY get() = Tbsettlebankhistory.TBSETTLEBANKHISTORY

    /**
     * The table <code>tbSoftBankHistory</code>.
     */
    val TBSOFTBANKHISTORY get() = Tbsoftbankhistory.TBSOFTBANKHISTORY

    /**
     * The table <code>tbSubscribe</code>.
     */
    val TBSUBSCRIBE get() = Tbsubscribe.TBSUBSCRIBE

    /**
     * The table <code>tbSubscribeAndroidHistory</code>.
     */
    val TBSUBSCRIBEANDROIDHISTORY get() = Tbsubscribeandroidhistory.TBSUBSCRIBEANDROIDHISTORY

    /**
     * The table <code>tbSubscribeIosHistory</code>.
     */
    val TBSUBSCRIBEIOSHISTORY get() = Tbsubscribeioshistory.TBSUBSCRIBEIOSHISTORY

    /**
     * The table <code>tbTossHistory</code>.
     */
    val TBTOSSHISTORY get() = Tbtosshistory.TBTOSSHISTORY

    /**
     * The table <code>tbWebMoneyHistory</code>.
     */
    val TBWEBMONEYHISTORY get() = Tbwebmoneyhistory.TBWEBMONEYHISTORY

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Tbadpopcornhistory.TBADPOPCORNHISTORY,
        Tbapplestorehistory.TBAPPLESTOREHISTORY,
        Tberrorlog.TBERRORLOG,
        Tbexchange.TBEXCHANGE,
        Tbexchangeamount.TBEXCHANGEAMOUNT,
        Tbexchangeamountdotmoneyhistory.TBEXCHANGEAMOUNTDOTMONEYHISTORY,
        Tbexchangedeposit.TBEXCHANGEDEPOSIT,
        Tbexchangedotmoneyproducts.TBEXCHANGEDOTMONEYPRODUCTS,
        Tbexchangedotmoneysignaturedata.TBEXCHANGEDOTMONEYSIGNATUREDATA,
        Tbexchangehistory.TBEXCHANGEHISTORY,
        Tbexchangerejectreason.TBEXCHANGEREJECTREASON,
        Tbexchangesubmitdocument.TBEXCHANGESUBMITDOCUMENT,
        Tbgiftcardhistory.TBGIFTCARDHISTORY,
        Tbitemproduct.TBITEMPRODUCT,
        Tbitempromotion.TBITEMPROMOTION,
        Tbitemstore.TBITEMSTORE,
        Tbpayment.TBPAYMENT,
        Tbpaymentmethod.TBPAYMENTMETHOD,
        Tbpaypalhistory.TBPAYPALHISTORY,
        Tbplaystorehistory.TBPLAYSTOREHISTORY,
        Tbpromotionhistory.TBPROMOTIONHISTORY,
        Tbsettlebankhistory.TBSETTLEBANKHISTORY,
        Tbsoftbankhistory.TBSOFTBANKHISTORY,
        Tbsubscribe.TBSUBSCRIBE,
        Tbsubscribeandroidhistory.TBSUBSCRIBEANDROIDHISTORY,
        Tbsubscribeioshistory.TBSUBSCRIBEIOSHISTORY,
        Tbtosshistory.TBTOSSHISTORY,
        Tbwebmoneyhistory.TBWEBMONEYHISTORY
    )
}
